# 感情チェック設問データ（120問）
# 参考尺度・理論: STAXI-2, NAS (Novaco), CAS (Snell), DAR-5,
#   Beck 認知的歪み, DERS, InAn (2025), K6, PANAS
#
# 全カテゴリ共通: 低スコア = 良好、高スコア = 要注意
# 逆転項目 (reverse=True): ポジティブな状態を測定 → (5-value) で変換

SCALE_LABELS = {
    1: "まったくそうでない",
    2: "少しそうだ",
    3: "かなりそうだ",
    4: "非常にそうだ",
}

QUESTIONS = [
    # ════════════════════════════════════════════════════════════════════
    # カテゴリ1: 怒りの状態 (anger_state) ── 25問
    # 参考: STAXI-2 State Anger, DAR-5, CAS
    # ════════════════════════════════════════════════════════════════════

    # --- 現在の怒り強度 (1-10) ---
    {"id": 1, "category": "anger_state", "subcategory": "intensity", "text": "今、イライラしている", "reverse": False,
     "explanation": "現在の怒り感情の強度を測定します（STAXI-2 State Anger 参考）。",
     "advice_high": "4-7-8呼吸法（4秒吸って7秒止めて8秒で吐く）を試してみましょう。",
     "advice_low": "穏やかな状態です。この感覚を意識に留めておきましょう。"},
    {"id": 2, "category": "anger_state", "subcategory": "intensity", "text": "今、怒りの感情がある", "reverse": False,
     "explanation": "怒り感情の存在を確認します。",
     "advice_high": "怒りを感じていることに気づけています。散歩や軽い運動でエネルギーを発散させましょう。",
     "advice_low": "穏やかな状態が続いています。"},
    {"id": 3, "category": "anger_state", "subcategory": "intensity", "text": "今、かっとなりそうな感覚がある", "reverse": False,
     "explanation": "怒りの爆発リスクを測定します（Novaco Arousal 参考）。",
     "advice_high": "その場を一度離れましょう。物理的な距離が感情的な距離を作ります。",
     "advice_low": "冷静を保てています。"},
    {"id": 4, "category": "anger_state", "subcategory": "intensity", "text": "今、ひどく腹が立っている", "reverse": False,
     "explanation": "強い怒り感情を測定します。",
     "advice_high": "強い怒りを感じている時は判断を避けましょう。10秒カウントしてから行動してください。",
     "advice_low": "落ち着いた状態です。"},
    {"id": 5, "category": "anger_state", "subcategory": "intensity", "text": "今、誰かに怒りをぶつけたくなっている", "reverse": False,
     "explanation": "怒りの外向き表出衝動を測定します（Novaco Behavioral 参考）。",
     "advice_high": "衝動を感じたら紙に気持ちを書き出してみましょう。書くことで感情が整理されます。",
     "advice_low": "感情の衝動が落ち着いています。"},
    {"id": 6, "category": "anger_state", "subcategory": "intensity", "text": "今、強い不満を感じている", "reverse": False,
     "explanation": "不満感は怒りの前段階になることがあります（CAS 参考）。",
     "advice_high": "不満の原因を具体的に書き出し、コントロールできることとそうでないことを分けてみましょう。",
     "advice_low": "満足度が高い状態です。"},
    {"id": 7, "category": "anger_state", "subcategory": "intensity", "text": "今、誰かを責めたい気持ちがある", "reverse": False,
     "explanation": "他責傾向の感情状態を測定します。",
     "advice_high": "相手の立場や事情を想像してみましょう。背景を知ると怒りが和らぐことがあります。",
     "advice_low": "他者への攻撃衝動が低い状態です。"},
    {"id": 8, "category": "anger_state", "subcategory": "intensity", "text": "今、落ち着いた気持ちでいる", "reverse": True,
     "explanation": "現在の穏やかさを測定します（逆転項目）。",
     "advice_high": "穏やかさを維持できています。",
     "advice_low": "気持ちが揺れている時は、まず呼吸に意識を向けてみましょう。"},
    {"id": 9, "category": "anger_state", "subcategory": "intensity", "text": "今、穏やかな気分だ", "reverse": True,
     "explanation": "穏やかさのレベルを測定する逆転項目です。",
     "advice_high": "穏やかな状態を大切にしてください。",
     "advice_low": "気持ちの波がある時は、好きな音楽を聴くなどリラックスできることを試しましょう。"},
    {"id": 10, "category": "anger_state", "subcategory": "intensity", "text": "今、何かを壊したくなるような怒りがある", "reverse": False,
     "explanation": "怒りの破壊的衝動を測定します（CAS 参考）。",
     "advice_high": "安全な方法でエネルギーを発散させましょう（枕を叩く、新聞紙を破るなど）。",
     "advice_low": "破壊的な衝動は感じられていません。"},

    # --- 怒りの頻度・持続 (11-17) ---
    {"id": 11, "category": "anger_state", "subcategory": "frequency", "text": "最近、些細なことでイライラすることが多い", "reverse": False,
     "explanation": "怒りの頻度を測定します（DAR-5 参考）。",
     "advice_high": "怒りのトリガーをリストアップし、事前に対処法を準備しておきましょう。",
     "advice_low": "怒りの閾値が適切に保たれています。"},
    {"id": 12, "category": "anger_state", "subcategory": "frequency", "text": "一度怒ると怒りが消えるまでに時間がかかる", "reverse": False,
     "explanation": "怒りの持続時間を測定します（DAR-5 参考）。",
     "advice_high": "運動・入浴・睡眠など、怒りをリセットするルーティンを作りましょう。",
     "advice_low": "怒りの回復が早い傾向があります。"},
    {"id": 13, "category": "anger_state", "subcategory": "frequency", "text": "最近、怒りが爆発した後に後悔することがある", "reverse": False,
     "explanation": "怒り爆発後の後悔は改善動機につながります。",
     "advice_high": "後悔は変化へのエネルギーです。次にどう対応するか具体的に計画しましょう。",
     "advice_low": "怒りのコントロールができています。"},
    {"id": 14, "category": "anger_state", "subcategory": "frequency", "text": "最近、怒りの感情がすぐに収まるようになった", "reverse": True,
     "explanation": "怒りの回復速度の改善を測定する逆転項目です。",
     "advice_high": "怒りへの対処力が向上しています。",
     "advice_low": "怒りが長引く場合は、リラクセーション技法を定期的に練習してみましょう。"},
    {"id": 15, "category": "anger_state", "subcategory": "frequency", "text": "最近、怒りを感じる頻度が増えている", "reverse": False,
     "explanation": "怒りの頻度変化を測定します。",
     "advice_high": "ストレス源が増えているかもしれません。生活のなかの負荷を見直してみましょう。",
     "advice_low": "怒りの頻度が安定しています。"},
    {"id": 16, "category": "anger_state", "subcategory": "frequency", "text": "最近、怒りの強さが以前より増している", "reverse": False,
     "explanation": "怒りの強度変化を測定します。",
     "advice_high": "怒りの強度が増している時は、早めに専門家に相談することも選択肢です。",
     "advice_low": "怒りの強度が安定しています。"},
    {"id": 17, "category": "anger_state", "subcategory": "frequency", "text": "最近、感情をうまくコントロールできていると感じる", "reverse": True,
     "explanation": "感情コントロールの自己効力感を測定する逆転項目です。",
     "advice_high": "自己コントロールの感覚が保たれています。",
     "advice_low": "感情のコントロールが難しいと感じたら、信頼できる人に話を聞いてもらいましょう。"},

    # --- 怒りの日常生活への影響 (18-25) ---
    {"id": 18, "category": "anger_state", "subcategory": "impact", "text": "怒りのせいで集中力が低下している", "reverse": False,
     "explanation": "怒りが認知機能に与える影響を測定します（CAS 参考）。",
     "advice_high": "集中力の低下を感じたら、5分間の呼吸瞑想を試してみましょう。",
     "advice_low": "集中力が維持できています。"},
    {"id": 19, "category": "anger_state", "subcategory": "impact", "text": "怒りのせいで睡眠に影響が出ている", "reverse": False,
     "explanation": "怒りが睡眠に与える影響を測定します（CAS 参考）。",
     "advice_high": "就寝前にリラクセーション技法（漸進的筋弛緩法など）を取り入れてみましょう。",
     "advice_low": "睡眠への影響はないようです。"},
    {"id": 20, "category": "anger_state", "subcategory": "impact", "text": "怒りのせいで対人関係が悪化している", "reverse": False,
     "explanation": "怒りが対人関係に与える影響を測定します（DAR-5 社会的干渉 参考）。",
     "advice_high": "大切な人との関係を守るために、怒りを感じた時の「タイムアウトルール」を決めましょう。",
     "advice_low": "対人関係への影響は少ない状態です。"},
    {"id": 21, "category": "anger_state", "subcategory": "impact", "text": "怒りのせいで仕事や日常の活動に支障が出ている", "reverse": False,
     "explanation": "怒りが日常機能に与える影響を測定します（CAS 参考）。",
     "advice_high": "怒りが日常に影響している場合は、専門家への相談を検討しましょう。",
     "advice_low": "日常活動に支障は出ていません。"},
    {"id": 22, "category": "anger_state", "subcategory": "impact", "text": "怒りのせいで食欲に変化がある", "reverse": False,
     "explanation": "怒りが食欲に与える影響を測定します（CAS 参考）。",
     "advice_high": "感情と食欲の関連に気づけています。規則正しい食事リズムを意識しましょう。",
     "advice_low": "食欲に問題はないようです。"},
    {"id": 23, "category": "anger_state", "subcategory": "impact", "text": "怒りのせいで判断力が鈍っている", "reverse": False,
     "explanation": "怒りが意思決定に与える影響を測定します（CAS 参考）。",
     "advice_high": "感情が高ぶっている時は重要な判断を避け、落ち着いてから決めましょう。",
     "advice_low": "判断力は維持されています。"},
    {"id": 24, "category": "anger_state", "subcategory": "impact", "text": "怒りのせいで疲れを感じている", "reverse": False,
     "explanation": "怒りが身体的疲労に与える影響を測定します（CAS 参考）。",
     "advice_high": "怒りはエネルギーを消耗します。十分な休息を取りましょう。",
     "advice_low": "怒りによる疲労は感じていません。"},
    {"id": 25, "category": "anger_state", "subcategory": "impact", "text": "怒りがあっても日常生活を普通に送れている", "reverse": True,
     "explanation": "怒りへの適応力を測定する逆転項目です。",
     "advice_high": "怒りがあっても機能を維持できています。",
     "advice_low": "怒りが日常に影響を与えています。生活のなかで無理していないか振り返りましょう。"},

    # ════════════════════════════════════════════════════════════════════
    # カテゴリ2: 認知パターン (cognitive_pattern) ── 25問
    # 参考: Beck 認知的歪み, Novaco Cognitive, Burns (1980)
    # ════════════════════════════════════════════════════════════════════

    # --- べき思考 (should statements) (26-30) ---
    {"id": 26, "category": "cognitive_pattern", "subcategory": "should_statements", "text": "「〜すべきだ」「〜であるべきだ」と考えることが多い", "reverse": False,
     "explanation": "べき思考は怒りの主要な認知的トリガーです（Beck CBT 理論）。",
     "advice_high": "「べき」を「できれば〜がいい」に置き換えてみましょう。柔軟な期待がストレスを減らします。",
     "advice_low": "柔軟な考え方ができています。"},
    {"id": 27, "category": "cognitive_pattern", "subcategory": "should_statements", "text": "他人は自分の期待通りに行動すべきだと感じる", "reverse": False,
     "explanation": "他者への要求水準の高さを測定します。",
     "advice_high": "他者をコントロールすることはできません。自分の反応だけがコントロール可能です。",
     "advice_low": "他者への期待が適切な水準にあります。"},
    {"id": 28, "category": "cognitive_pattern", "subcategory": "should_statements", "text": "物事は公平であるべきだと強く思う", "reverse": False,
     "explanation": "公平さへの固着的信念を測定します。",
     "advice_high": "不公平な状況は存在します。変えられることと受け入れるべきことを区別しましょう。",
     "advice_low": "公平さへの期待が適切です。"},
    {"id": 29, "category": "cognitive_pattern", "subcategory": "should_statements", "text": "自分のルールに反することを許せない", "reverse": False,
     "explanation": "規則への固執度を測定します。",
     "advice_high": "自分のルールが本当に絶対的なものか、振り返ってみましょう。",
     "advice_low": "ルールに対して柔軟さがあります。"},
    {"id": 30, "category": "cognitive_pattern", "subcategory": "should_statements", "text": "期待を柔軟に調整できる", "reverse": True,
     "explanation": "認知の柔軟性を測定する逆転項目です。",
     "advice_high": "柔軟な思考ができています。",
     "advice_low": "期待が固定的になりがちです。小さなところから「まあいいか」を練習しましょう。"},

    # --- 読心術 (mind reading) (31-35) ---
    {"id": 31, "category": "cognitive_pattern", "subcategory": "mind_reading", "text": "他人が自分を悪く思っていると感じることがある", "reverse": False,
     "explanation": "読心術は根拠なく他者の思考を推測する認知的歪みです（Burns 1980）。",
     "advice_high": "実際に確認せずに相手の考えを決めつけていませんか？直接聞いてみましょう。",
     "advice_low": "他者の意図を過度に推測していません。"},
    {"id": 32, "category": "cognitive_pattern", "subcategory": "mind_reading", "text": "相手の表情や態度から悪意を読み取ってしまう", "reverse": False,
     "explanation": "敵意帰属バイアスを測定します（Novaco Cognitive 参考）。",
     "advice_high": "表情には様々な解釈が可能です。3つの異なる解釈を考えてみましょう。",
     "advice_low": "他者の表情を冷静に読み取れています。"},
    {"id": 33, "category": "cognitive_pattern", "subcategory": "mind_reading", "text": "人の行動の裏に悪い意図があると疑ってしまう", "reverse": False,
     "explanation": "敵意帰属の傾向を測定します。",
     "advice_high": "疑念が浮かんだら「別の可能性」を3つ考えてみましょう。",
     "advice_low": "他者の意図を好意的に解釈できています。"},
    {"id": 34, "category": "cognitive_pattern", "subcategory": "mind_reading", "text": "自分は周囲から嫌われていると思うことがある", "reverse": False,
     "explanation": "対人場面での被害的認知を測定します。",
     "advice_high": "思い込みかどうか、客観的な事実を確認してみましょう。",
     "advice_low": "対人関係での認知が安定しています。"},
    {"id": 35, "category": "cognitive_pattern", "subcategory": "mind_reading", "text": "他人の行動を好意的に解釈できることが多い", "reverse": True,
     "explanation": "好意的解釈の傾向を測定する逆転項目です。",
     "advice_high": "ポジティブな解釈ができています。",
     "advice_low": "他者の行動をネガティブに捉えがちです。「もし親友の行動だったら？」と考えてみましょう。"},

    # --- 破局化 (catastrophizing) (36-39) ---
    {"id": 36, "category": "cognitive_pattern", "subcategory": "catastrophizing", "text": "小さなトラブルでも最悪の結果を想像してしまう", "reverse": False,
     "explanation": "破局化は出来事の結果を過大に悪く見積もる認知的歪みです。",
     "advice_high": "最悪のシナリオの実現可能性を0〜100%で数値化してみましょう。",
     "advice_low": "出来事を適切な規模で捉えられています。"},
    {"id": 37, "category": "cognitive_pattern", "subcategory": "catastrophizing", "text": "嫌なことが起きると「もうダメだ」と感じてしまう", "reverse": False,
     "explanation": "絶望的な解釈の傾向を測定します。",
     "advice_high": "「もうダメだ」と感じた時、過去に同じように感じて乗り越えた経験を思い出しましょう。",
     "advice_low": "困難に対して冷静に対処できています。"},
    {"id": 38, "category": "cognitive_pattern", "subcategory": "catastrophizing", "text": "問題を実際以上に大きく感じてしまう", "reverse": False,
     "explanation": "拡大解釈の傾向を測定します。",
     "advice_high": "1年後にこの問題を覚えているか？と自問してみましょう。",
     "advice_low": "問題を適切なサイズで捉えられています。"},
    {"id": 39, "category": "cognitive_pattern", "subcategory": "catastrophizing", "text": "困難な状況でも「なんとかなる」と思える", "reverse": True,
     "explanation": "楽観的対処を測定する逆転項目です。",
     "advice_high": "適切な楽観性を持てています。",
     "advice_low": "困難を過大に感じています。過去の成功体験を振り返ってみましょう。"},

    # --- 反芻 (rumination) (40-43) ---
    {"id": 40, "category": "cognitive_pattern", "subcategory": "rumination", "text": "嫌な出来事を何度も頭の中で繰り返し考えてしまう", "reverse": False,
     "explanation": "怒りの反芻はNovaco認知ドメインの主要要素です。",
     "advice_high": "反芻に気づいたら「ストップ」と心の中で唱え、今の感覚（五感）に意識を戻しましょう。",
     "advice_low": "思考の切り替えがうまくできています。"},
    {"id": 41, "category": "cognitive_pattern", "subcategory": "rumination", "text": "怒りの場面を頭の中で何度も再生してしまう", "reverse": False,
     "explanation": "怒り場面の反芻を測定します。",
     "advice_high": "頭の中の再生を止めるために、身体を動かすか別の活動に集中しましょう。",
     "advice_low": "過去の怒りに囚われていません。"},
    {"id": 42, "category": "cognitive_pattern", "subcategory": "rumination", "text": "「あの時こう言えばよかった」と後から考え続ける", "reverse": False,
     "explanation": "事後反芻を測定します。",
     "advice_high": "過去は変えられません。「次に同じ場面が来たらどうするか」に意識を向けましょう。",
     "advice_low": "過去の出来事を適切に手放せています。"},
    {"id": 43, "category": "cognitive_pattern", "subcategory": "rumination", "text": "嫌な出来事を考えるのを自分で止められる", "reverse": True,
     "explanation": "反芻停止能力を測定する逆転項目です。",
     "advice_high": "思考のコントロール力があります。",
     "advice_low": "思考が繰り返される時は、紙に書き出して「外に出す」ことで軽減できます。"},

    # --- 敵意帰属・ラベリング・白黒思考 (44-50) ---
    {"id": 44, "category": "cognitive_pattern", "subcategory": "hostile_attribution", "text": "誰かがミスをすると「わざとだ」と思ってしまう", "reverse": False,
     "explanation": "敵意帰属バイアスは怒りの認知的要因です（Novaco Cognitive）。",
     "advice_high": "ミスの原因を「意図」ではなく「状況」で考える練習をしましょう。",
     "advice_low": "他者のミスを状況的に理解できています。"},
    {"id": 45, "category": "cognitive_pattern", "subcategory": "hostile_attribution", "text": "自分に不利なことが起きると「狙われている」と感じる", "reverse": False,
     "explanation": "被害的認知を測定します。",
     "advice_high": "不利な出来事が本当に自分を狙ったものか、客観的に検証してみましょう。",
     "advice_low": "出来事を客観的に捉えられています。"},
    {"id": 46, "category": "cognitive_pattern", "subcategory": "labeling", "text": "怒りを感じた相手に「最低だ」「バカだ」などのレッテルを貼ってしまう", "reverse": False,
     "explanation": "ラベリングは人格全体を否定する認知的歪みです（Burns 1980）。",
     "advice_high": "行動と人格を分けましょう。「あの行動は問題だ」と「あの人は最低だ」は違います。",
     "advice_low": "人格と行動を区別できています。"},
    {"id": 47, "category": "cognitive_pattern", "subcategory": "labeling", "text": "自分自身に「ダメな人間だ」とレッテルを貼ることがある", "reverse": False,
     "explanation": "自己へのラベリングを測定します。",
     "advice_high": "「ダメな人間」ではなく「今回はうまくいかなかった」と言い換えてみましょう。",
     "advice_low": "自己評価が安定しています。"},
    {"id": 48, "category": "cognitive_pattern", "subcategory": "black_white", "text": "物事を「完全に正しい」か「完全に間違い」かで判断しがちだ", "reverse": False,
     "explanation": "白黒思考（二分法的思考）を測定します（Beck 認知的歪み）。",
     "advice_high": "グレーゾーンを認めましょう。0か100ではなく、30%くらい正しいかもしれません。",
     "advice_low": "バランスの取れた判断ができています。"},
    {"id": 49, "category": "cognitive_pattern", "subcategory": "black_white", "text": "一つの失敗で「何もかもダメだ」と感じてしまう", "reverse": False,
     "explanation": "過度の一般化を測定します。",
     "advice_high": "一つの出来事と人生全体を切り離しましょう。失敗は一部分です。",
     "advice_low": "出来事を適切な範囲で捉えられています。"},
    {"id": 50, "category": "cognitive_pattern", "subcategory": "balanced", "text": "物事にはいろいろな見方があると考えられる", "reverse": True,
     "explanation": "認知的柔軟性を測定する逆転項目です。",
     "advice_high": "多角的な視点を持てています。",
     "advice_low": "一つの見方に固定されがちです。別の視点を意識的に探してみましょう。"},

    # ════════════════════════════════════════════════════════════════════
    # カテゴリ3: 身体反応 (physiological) ── 15問
    # 参考: Novaco Arousal, InAn Factor 1 (覚醒管理困難)
    # ════════════════════════════════════════════════════════════════════

    # --- 心血管系 (51-55) ---
    {"id": 51, "category": "physiological", "subcategory": "cardiovascular", "text": "今、心臓がドキドキしている", "reverse": False,
     "explanation": "怒りの心血管系反応を測定します（Novaco Arousal）。",
     "advice_high": "ゆっくりとした深呼吸で副交感神経を活性化させましょう。",
     "advice_low": "心拍が穏やかです。"},
    {"id": 52, "category": "physiological", "subcategory": "cardiovascular", "text": "今、頭に血が上っている感じがする", "reverse": False,
     "explanation": "頭部への血流増加感を測定します。",
     "advice_high": "冷たい水を飲む・手首を冷やすなど物理的なクールダウンが有効です。",
     "advice_low": "身体が穏やかな状態です。"},
    {"id": 53, "category": "physiological", "subcategory": "cardiovascular", "text": "今、顔が熱くなっている", "reverse": False,
     "explanation": "顔面の熱感は怒りの身体的サインです。",
     "advice_high": "冷たいタオルを顔に当てると、すぐにクールダウンできます。",
     "advice_low": "顔面の温度が通常です。"},
    {"id": 54, "category": "physiological", "subcategory": "cardiovascular", "text": "今、呼吸が浅く速くなっている", "reverse": False,
     "explanation": "呼吸の変化は怒りの初期サインです。",
     "advice_high": "腹式呼吸に切り替えましょう。お腹に手を当てて、膨らむのを感じながら呼吸します。",
     "advice_low": "呼吸が落ち着いています。"},
    {"id": 55, "category": "physiological", "subcategory": "cardiovascular", "text": "今、身体がリラックスしている", "reverse": True,
     "explanation": "身体のリラックス度を測定する逆転項目です。",
     "advice_high": "身体のリラックスが保てています。",
     "advice_low": "身体が緊張しています。漸進的筋弛緩法を試してみましょう。"},

    # --- 筋緊張 (56-60) ---
    {"id": 56, "category": "physiological", "subcategory": "muscle_tension", "text": "今、肩や首が緊張している", "reverse": False,
     "explanation": "肩・首の筋緊張は怒りの典型的な身体反応です（InAn Factor 1）。",
     "advice_high": "肩を耳まで上げて5秒キープし、一気に力を抜く動作を3回繰り返しましょう。",
     "advice_low": "肩・首の緊張は感じられていません。"},
    {"id": 57, "category": "physiological", "subcategory": "muscle_tension", "text": "今、歯を食いしばっている、または顎が緊張している", "reverse": False,
     "explanation": "顎の緊張を測定します。",
     "advice_high": "口を軽く開けて顎の力を抜きましょう。舌を上あごから離すと自然に力が抜けます。",
     "advice_low": "顎の緊張はありません。"},
    {"id": 58, "category": "physiological", "subcategory": "muscle_tension", "text": "今、拳を握りしめている、または手に力が入っている", "reverse": False,
     "explanation": "手の緊張を測定します。",
     "advice_high": "両手をグーパーと開閉し、力を入れてから抜く動作を繰り返しましょう。",
     "advice_low": "手がリラックスしています。"},
    {"id": 59, "category": "physiological", "subcategory": "muscle_tension", "text": "今、身体全体がこわばっている感じがする", "reverse": False,
     "explanation": "全身の筋緊張を測定します（InAn Factor 1）。",
     "advice_high": "全身のストレッチを5分間行いましょう。特に背中と脚を伸ばすと効果的です。",
     "advice_low": "身体のこわばりは感じられていません。"},
    {"id": 60, "category": "physiological", "subcategory": "muscle_tension", "text": "今、身体が軽くて楽な状態だ", "reverse": True,
     "explanation": "身体の軽さを測定する逆転項目です。",
     "advice_high": "身体が楽な状態を維持できています。",
     "advice_low": "身体の重さを感じています。軽いストレッチや散歩で身体をほぐしましょう。"},

    # --- その他の身体反応 (61-65) ---
    {"id": 61, "category": "physiological", "subcategory": "somatic", "text": "今、胃がキリキリする、またはお腹に違和感がある", "reverse": False,
     "explanation": "消化器系の怒り反応を測定します（InAn Factor 1）。",
     "advice_high": "温かい飲み物をゆっくり飲んで、お腹を落ち着かせましょう。",
     "advice_low": "消化器系に問題はないようです。"},
    {"id": 62, "category": "physiological", "subcategory": "somatic", "text": "今、手足が震えている、またはそわそわしている", "reverse": False,
     "explanation": "身体的な不安・覚醒反応を測定します。",
     "advice_high": "両足を床につけ、足裏の感覚に集中する「グラウンディング」を試しましょう。",
     "advice_low": "身体が安定しています。"},
    {"id": 63, "category": "physiological", "subcategory": "somatic", "text": "今、汗をかいている（運動以外で）", "reverse": False,
     "explanation": "交感神経系の活性化を測定します。",
     "advice_high": "涼しい場所に移動し、ゆっくりと深呼吸をしましょう。",
     "advice_low": "自律神経が安定しています。"},
    {"id": 64, "category": "physiological", "subcategory": "somatic", "text": "今、頭痛がする", "reverse": False,
     "explanation": "緊張性頭痛は怒りの身体症状の一つです。",
     "advice_high": "こめかみを優しくマッサージし、目を閉じて5分間休みましょう。",
     "advice_low": "頭痛は感じていません。"},
    {"id": 65, "category": "physiological", "subcategory": "somatic", "text": "今、身体的に心地よい状態だ", "reverse": True,
     "explanation": "全般的な身体的快適さを測定する逆転項目です。",
     "advice_high": "身体的に快適な状態です。",
     "advice_low": "身体の不快感がある場合は、ストレッチや深呼吸で和らげましょう。"},

    # ════════════════════════════════════════════════════════════════════
    # カテゴリ4: 行動傾向 (behavioral) ── 20問
    # 参考: Novaco Behavioral, STAXI-2 Anger Expression
    # ════════════════════════════════════════════════════════════════════

    # --- 言語的攻撃 (66-70) ---
    {"id": 66, "category": "behavioral", "subcategory": "verbal_aggression", "text": "今、誰かに怒鳴りたい気持ちがある", "reverse": False,
     "explanation": "言語的攻撃衝動を測定します（Novaco Behavioral）。",
     "advice_high": "大声を出したい衝動がある時は、一人の場所で声に出してみましょう。",
     "advice_low": "声の衝動がコントロールできています。"},
    {"id": 67, "category": "behavioral", "subcategory": "verbal_aggression", "text": "最近、つい嫌味や皮肉を言ってしまうことがある", "reverse": False,
     "explanation": "間接的な言語攻撃を測定します。",
     "advice_high": "皮肉の代わりに「私は〜と感じている」というI（アイ）メッセージで伝えましょう。",
     "advice_low": "建設的なコミュニケーションができています。"},
    {"id": 68, "category": "behavioral", "subcategory": "verbal_aggression", "text": "最近、相手を傷つける言葉を口にしてしまうことがある", "reverse": False,
     "explanation": "攻撃的な言語表出を測定します。",
     "advice_high": "言葉を発する前に3秒数えましょう。「この言葉は相手を傷つけるか」を確認してください。",
     "advice_low": "言葉のコントロールができています。"},
    {"id": 69, "category": "behavioral", "subcategory": "verbal_aggression", "text": "最近、声を荒げることが増えている", "reverse": False,
     "explanation": "声量の増加を測定します。",
     "advice_high": "意識的に声のトーンを下げる練習をしましょう。低い声はリラックス効果もあります。",
     "advice_low": "声のコントロールが適切です。"},
    {"id": 70, "category": "behavioral", "subcategory": "verbal_aggression", "text": "怒りを感じても冷静に話せることが多い", "reverse": True,
     "explanation": "冷静なコミュニケーション能力を測定する逆転項目です。",
     "advice_high": "怒りの中でも冷静に話す力があります。",
     "advice_low": "怒りの時に冷静さを保つため、話す前に深呼吸3回を習慣にしましょう。"},

    # --- 身体的・行動的攻撃 (71-75) ---
    {"id": 71, "category": "behavioral", "subcategory": "physical_aggression", "text": "今、物を投げたり叩いたりしたい衝動がある", "reverse": False,
     "explanation": "物理的攻撃衝動を測定します（Novaco Behavioral）。",
     "advice_high": "物を壊す代わりに、氷を握りしめるか、クッションを力いっぱい握りましょう。",
     "advice_low": "物理的な衝動は感じていません。"},
    {"id": 72, "category": "behavioral", "subcategory": "physical_aggression", "text": "最近、ドアを強く閉めたり物に当たったりすることがある", "reverse": False,
     "explanation": "間接的な物理的攻撃を測定します。",
     "advice_high": "物に当たる代わりに、その場でスクワットを10回してみましょう。",
     "advice_low": "物理的な行動が抑制されています。"},
    {"id": 73, "category": "behavioral", "subcategory": "physical_aggression", "text": "怒りで衝動的な行動をとりそうになることがある", "reverse": False,
     "explanation": "衝動性を測定します。",
     "advice_high": "衝動を感じたら「STOP」と自分に言い聞かせ、6秒待ちましょう（アンガーマネジメントの6秒ルール）。",
     "advice_low": "衝動のコントロールができています。"},
    {"id": 74, "category": "behavioral", "subcategory": "physical_aggression", "text": "最近、自分を傷つけたいと思うことがある", "reverse": False,
     "explanation": "自傷衝動を測定します。高スコアの場合は専門家への相談を推奨します。",
     "advice_high": "自分を傷つけたい気持ちがある時は、信頼できる人や専門家（いのちの電話: 0120-783-556）に相談してください。",
     "advice_low": "自傷衝動は感じていません。"},
    {"id": 75, "category": "behavioral", "subcategory": "physical_aggression", "text": "衝動的な行動を起こす前に立ち止まれることが多い", "reverse": True,
     "explanation": "衝動制御能力を測定する逆転項目です。",
     "advice_high": "衝動の前に立ち止まる力があります。",
     "advice_low": "衝動的になりがちです。行動の前に「10秒ルール」を設けましょう。"},

    # --- 抑制・回避 (76-80) ---
    {"id": 76, "category": "behavioral", "subcategory": "suppression", "text": "怒りを我慢して押し殺すことが多い", "reverse": False,
     "explanation": "怒りの過度な抑制を測定します（STAXI-2 Anger-In）。",
     "advice_high": "抑制しすぎは心身に悪影響です。安全な方法で感情を表現する練習をしましょう。",
     "advice_low": "感情の表現が適切にできています。"},
    {"id": 77, "category": "behavioral", "subcategory": "suppression", "text": "怒りを感じても表に出さないようにしている", "reverse": False,
     "explanation": "感情表出の抑制を測定します。",
     "advice_high": "感情を出さないことと感情を適切に伝えることは違います。I メッセージで気持ちを伝えましょう。",
     "advice_low": "感情表出のバランスが取れています。"},
    {"id": 78, "category": "behavioral", "subcategory": "suppression", "text": "怒りを感じる状況を避けるために人と距離を置くことがある", "reverse": False,
     "explanation": "回避行動を測定します。",
     "advice_high": "一時的な距離は有効ですが、長期的な回避は問題を悪化させます。落ち着いてから向き合いましょう。",
     "advice_low": "適切に状況と向き合えています。"},
    {"id": 79, "category": "behavioral", "subcategory": "suppression", "text": "怒りの感情を内に溜め込んでいると感じる", "reverse": False,
     "explanation": "感情の蓄積を測定します。",
     "advice_high": "感情日記をつけて、溜まった感情を「書いて出す」習慣を作りましょう。",
     "advice_low": "感情の蓄積が少ない状態です。"},
    {"id": 80, "category": "behavioral", "subcategory": "suppression", "text": "自分の怒りを適切な方法で表現できていると思う", "reverse": True,
     "explanation": "適切な感情表現の自己評価を測定する逆転項目です。",
     "advice_high": "怒りの表現が適切にできています。",
     "advice_low": "怒りの表現方法を見直してみましょう。「感情」と「要求」を分けて伝える練習が有効です。"},

    # --- 建設的対処 (81-85) ---
    {"id": 81, "category": "behavioral", "subcategory": "constructive", "text": "怒りを感じた時に深呼吸やリラクセーション技法を使える", "reverse": True,
     "explanation": "建設的な対処行動を測定する逆転項目です。",
     "advice_high": "リラクセーション技法が身についています。",
     "advice_low": "深呼吸を普段から練習しておくと、怒りの場面でも使えるようになります。"},
    {"id": 82, "category": "behavioral", "subcategory": "constructive", "text": "怒りを感じた時にその場を離れてクールダウンできる", "reverse": True,
     "explanation": "タイムアウト行動を測定する逆転項目です。",
     "advice_high": "タイムアウトが上手に使えています。",
     "advice_low": "「ちょっと離れます」と宣言してその場を離れる練習をしましょう。"},
    {"id": 83, "category": "behavioral", "subcategory": "constructive", "text": "怒りの原因について冷静に話し合うことができる", "reverse": True,
     "explanation": "建設的な対話能力を測定する逆転項目です。",
     "advice_high": "冷静な対話ができています。",
     "advice_low": "話し合いの前に「何を伝えたいか」を整理してからにしましょう。"},
    {"id": 84, "category": "behavioral", "subcategory": "constructive", "text": "怒りのエネルギーを運動や活動に変換できる", "reverse": True,
     "explanation": "怒りの昇華を測定する逆転項目です。",
     "advice_high": "怒りのエネルギーを建設的に活用できています。",
     "advice_low": "怒りを感じたら散歩や運動に切り替える習慣を作りましょう。"},
    {"id": 85, "category": "behavioral", "subcategory": "constructive", "text": "自分なりの怒りへの対処法を持っている", "reverse": True,
     "explanation": "対処法のレパートリーを測定する逆転項目です。",
     "advice_high": "自分なりの対処法を確立できています。",
     "advice_low": "自分に合った対処法を見つけることが大切です。いくつかの方法を試してみましょう。"},

    # ════════════════════════════════════════════════════════════════════
    # カテゴリ5: 感情調節 (emotion_regulation) ── 20問
    # 参考: DERS (Gratz & Roemer 2004), InAn Factor 2, CERQ
    # ════════════════════════════════════════════════════════════════════

    # --- 感情の認識・明確さ (86-90) ---
    {"id": 86, "category": "emotion_regulation", "subcategory": "awareness", "text": "今の自分の感情が何なのかよくわからない", "reverse": False,
     "explanation": "感情の明確さの欠如を測定します（DERS 参考）。",
     "advice_high": "感情に名前をつけてみましょう。「怒り」「悲しみ」「不安」「失望」など。",
     "advice_low": "自分の感情をよく理解できています。"},
    {"id": 87, "category": "emotion_regulation", "subcategory": "awareness", "text": "自分が何に怒っているのか分からないことがある", "reverse": False,
     "explanation": "怒りの原因認識の困難を測定します。",
     "advice_high": "怒りの下にある本当の感情を探ってみましょう。悲しみ・不安・失望が隠れていることがあります。",
     "advice_low": "怒りの原因を認識できています。"},
    {"id": 88, "category": "emotion_regulation", "subcategory": "awareness", "text": "自分の感情の変化に気づくことができる", "reverse": True,
     "explanation": "感情のモニタリング能力を測定する逆転項目です。",
     "advice_high": "感情の変化に敏感です。このスキルは感情調節の基盤です。",
     "advice_low": "感情日記をつけると、自分の感情パターンに気づきやすくなります。"},
    {"id": 89, "category": "emotion_regulation", "subcategory": "awareness", "text": "感情を言葉にするのが難しい", "reverse": False,
     "explanation": "感情の言語化困難を測定します。",
     "advice_high": "感情語彙を増やしましょう。「嬉しい」「悲しい」以外の感情ワードリストを作ってみてください。",
     "advice_low": "感情を言葉にできています。"},
    {"id": 90, "category": "emotion_regulation", "subcategory": "awareness", "text": "今、自分がどんな気持ちか明確に説明できる", "reverse": True,
     "explanation": "感情の明確さを測定する逆転項目です。",
     "advice_high": "感情を明確に理解できています。",
     "advice_low": "感情が混乱している時は、「体のどこに何を感じるか」から探ってみましょう。"},

    # --- 感情の受容 (91-95) ---
    {"id": 91, "category": "emotion_regulation", "subcategory": "acceptance", "text": "怒りを感じる自分を責めてしまう", "reverse": False,
     "explanation": "感情への自己批判を測定します（DERS 参考）。",
     "advice_high": "怒りは自然な感情です。感じること自体を否定せず、「怒っているんだな」と認めましょう。",
     "advice_low": "感情を自然に受け入れられています。"},
    {"id": 92, "category": "emotion_regulation", "subcategory": "acceptance", "text": "ネガティブな感情を感じると恥ずかしいと思う", "reverse": False,
     "explanation": "感情への羞恥心を測定します（InAn Factor 2 参考）。",
     "advice_high": "すべての感情には意味があります。恥ずかしいと感じる必要はありません。",
     "advice_low": "感情への受容度が高いです。"},
    {"id": 93, "category": "emotion_regulation", "subcategory": "acceptance", "text": "感情的になることは弱さだと思う", "reverse": False,
     "explanation": "感情への否定的信念を測定します。",
     "advice_high": "感情を感じることは人間の強さです。感情に気づけることこそが成長の第一歩です。",
     "advice_low": "感情を適切に捉えられています。"},
    {"id": 94, "category": "emotion_regulation", "subcategory": "acceptance", "text": "つらい感情も自分の一部として受け入れられる", "reverse": True,
     "explanation": "感情の受容能力を測定する逆転項目です。",
     "advice_high": "感情を受け入れる力があります。",
     "advice_low": "つらい感情も「今の自分の状態」として認めてみましょう。"},
    {"id": 95, "category": "emotion_regulation", "subcategory": "acceptance", "text": "怒りは自然な感情だと思える", "reverse": True,
     "explanation": "怒りへの受容度を測定する逆転項目です。",
     "advice_high": "怒りを自然な感情として認められています。",
     "advice_low": "怒りを「悪い感情」と決めつけず、「何かが侵害されたサイン」と捉えてみましょう。"},

    # --- 衝動制御 (96-100) ---
    {"id": 96, "category": "emotion_regulation", "subcategory": "impulse_control", "text": "感情が高ぶると自分の行動をコントロールしにくい", "reverse": False,
     "explanation": "感情下での行動制御困難を測定します（DERS 参考）。",
     "advice_high": "感情が高ぶった時の「行動プラン」を事前に決めておきましょう（例: その場を離れる）。",
     "advice_low": "感情下でも行動をコントロールできています。"},
    {"id": 97, "category": "emotion_regulation", "subcategory": "impulse_control", "text": "怒りを感じると後先考えずに行動してしまう", "reverse": False,
     "explanation": "衝動的行動傾向を測定します。",
     "advice_high": "「行動する前に10秒待つ」を習慣にしましょう。衝動は波のように去ります。",
     "advice_low": "慎重な行動ができています。"},
    {"id": 98, "category": "emotion_regulation", "subcategory": "impulse_control", "text": "感情的になっている時に冷静な判断ができない", "reverse": False,
     "explanation": "感情下での判断力低下を測定します。",
     "advice_high": "感情が強い時は重要な判断を翌日に延期しましょう。",
     "advice_low": "感情と判断を分離できています。"},
    {"id": 99, "category": "emotion_regulation", "subcategory": "impulse_control", "text": "感情が高ぶっても行動は慎重に選べる", "reverse": True,
     "explanation": "感情下での慎重な行動選択を測定する逆転項目です。",
     "advice_high": "感情と行動を分離できています。",
     "advice_low": "感情と行動を切り離す練習として「一拍置く」を意識しましょう。"},
    {"id": 100, "category": "emotion_regulation", "subcategory": "impulse_control", "text": "怒りの衝動が来ても、それを行動に移さない自信がある", "reverse": True,
     "explanation": "衝動制御の自己効力感を測定する逆転項目です。",
     "advice_high": "衝動への自信があります。",
     "advice_low": "衝動を行動に移さない練習として、6秒ルール（怒りのピークは6秒）を覚えておきましょう。"},

    # --- 対処方略 (101-105) ---
    {"id": 101, "category": "emotion_regulation", "subcategory": "coping", "text": "つらい感情への対処法が見つからないと感じる", "reverse": False,
     "explanation": "対処方略の欠如を測定します（DERS 参考）。",
     "advice_high": "対処法リスト（散歩・深呼吸・音楽・書き出しなど）を紙に書いて持ち歩きましょう。",
     "advice_low": "対処法を持てています。"},
    {"id": 102, "category": "emotion_regulation", "subcategory": "coping", "text": "嫌な気分の時に気分転換の方法が思いつかない", "reverse": False,
     "explanation": "気分転換能力の欠如を測定します。",
     "advice_high": "気分転換リストを事前に作っておくと、辛い時にすぐ使えます。",
     "advice_low": "気分転換の手段を持っています。"},
    {"id": 103, "category": "emotion_regulation", "subcategory": "coping", "text": "ネガティブな感情から立ち直るのに時間がかかる", "reverse": False,
     "explanation": "感情回復の遅さを測定します。",
     "advice_high": "回復に時間がかかる時は、意識的に「今、ここ」に注意を向ける練習（マインドフルネス）が有効です。",
     "advice_low": "感情の回復が適切な速さです。"},
    {"id": 104, "category": "emotion_regulation", "subcategory": "coping", "text": "困った時に自分なりの対処法を使って乗り越えられる", "reverse": True,
     "explanation": "対処の自己効力感を測定する逆転項目です（CERQ 参考）。",
     "advice_high": "自分なりの対処法を活用できています。",
     "advice_low": "対処法のレパートリーを広げましょう。認知的再評価やリラクセーションを試してみてください。"},
    {"id": 105, "category": "emotion_regulation", "subcategory": "coping", "text": "感情が辛い時でも「これはいつか和らぐ」と思える", "reverse": True,
     "explanation": "感情の一時性への理解を測定する逆転項目です。",
     "advice_high": "感情は永続的ではないと理解できています。",
     "advice_low": "感情は波のようなものです。必ず引いていくことを覚えておきましょう。"},

    # ════════════════════════════════════════════════════════════════════
    # カテゴリ6: 心理的状態 (psychological_state) ── 15問
    # 参考: K6 (Kessler 2003), PANAS (Watson 1988)
    # ════════════════════════════════════════════════════════════════════

    # --- ネガティブ感情 (106-110) ---
    {"id": 106, "category": "psychological_state", "subcategory": "negative_affect", "text": "今、不安や心配を感じている", "reverse": False,
     "explanation": "現在の不安レベルを測定します（K6 参考）。",
     "advice_high": "不安を感じたら、4-7-8呼吸法でリラックスしましょう。",
     "advice_low": "不安が低い状態です。"},
    {"id": 107, "category": "psychological_state", "subcategory": "negative_affect", "text": "今、気分が落ち込んでいる", "reverse": False,
     "explanation": "現在の抑うつレベルを測定します（K6 参考）。",
     "advice_high": "気分の落ち込みがある時は、軽い運動や日光浴が効果的です。",
     "advice_low": "気分が安定しています。"},
    {"id": 108, "category": "psychological_state", "subcategory": "negative_affect", "text": "今、緊張やプレッシャーを感じている", "reverse": False,
     "explanation": "現在のストレスレベルを測定します。",
     "advice_high": "緊張を感じたら、漸進的筋弛緩法を試しましょう。",
     "advice_low": "リラックスした状態です。"},
    {"id": 109, "category": "psychological_state", "subcategory": "negative_affect", "text": "今、絶望的な気持ちがある", "reverse": False,
     "explanation": "絶望感を測定します（K6 参考）。高スコアの場合は専門家への相談を推奨します。",
     "advice_high": "絶望的な気持ちが続く場合は、専門家（よりそいホットライン: 0120-279-338）に相談してください。",
     "advice_low": "前向きな気持ちが保たれています。"},
    {"id": 110, "category": "psychological_state", "subcategory": "negative_affect", "text": "今、自分は価値がないと感じている", "reverse": False,
     "explanation": "自己価値感の低下を測定します（K6 参考）。",
     "advice_high": "あなたには価値があります。自分の良いところを3つ書き出してみましょう。",
     "advice_low": "自己価値感が保たれています。"},

    # --- ポジティブ感情 (111-115) ---
    {"id": 111, "category": "psychological_state", "subcategory": "positive_affect", "text": "今、前向きな気持ちがある", "reverse": True,
     "explanation": "ポジティブ感情を測定する逆転項目です（PANAS 参考）。",
     "advice_high": "前向きな気持ちを大切にしてください。",
     "advice_low": "気分を上げるために、好きなことや楽しかった思い出を振り返りましょう。"},
    {"id": 112, "category": "psychological_state", "subcategory": "positive_affect", "text": "今、活力やエネルギーを感じている", "reverse": True,
     "explanation": "活力レベルを測定する逆転項目です（PANAS 参考）。",
     "advice_high": "エネルギーが充実しています。",
     "advice_low": "エネルギー不足を感じたら、軽い運動や十分な睡眠を心がけましょう。"},
    {"id": 113, "category": "psychological_state", "subcategory": "positive_affect", "text": "今、希望や期待を感じることがある", "reverse": True,
     "explanation": "希望感を測定する逆転項目です。",
     "advice_high": "希望を持てています。",
     "advice_low": "小さな楽しみや目標を設定して、前を向くきっかけを作りましょう。"},
    {"id": 114, "category": "psychological_state", "subcategory": "positive_affect", "text": "今、誰かとつながっている感覚がある", "reverse": True,
     "explanation": "社会的つながり感を測定する逆転項目です。",
     "advice_high": "つながりの感覚が保たれています。",
     "advice_low": "孤独を感じたら、信頼できる人に連絡を取ってみましょう。"},
    {"id": 115, "category": "psychological_state", "subcategory": "positive_affect", "text": "今、自分の生活にある程度満足している", "reverse": True,
     "explanation": "生活満足度を測定する逆転項目です。",
     "advice_high": "生活への満足感があります。",
     "advice_low": "不満がある場合は、変えられることから少しずつ改善していきましょう。"},

    # --- 全般的な心理状態 (116-120) ---
    {"id": 116, "category": "psychological_state", "subcategory": "general", "text": "今、何をするにも気力がわかない", "reverse": False,
     "explanation": "気力の低下を測定します（K6 参考）。",
     "advice_high": "気力が出ない時は、「まず1分だけやる」と決めて行動してみましょう。",
     "advice_low": "気力が保たれています。"},
    {"id": 117, "category": "psychological_state", "subcategory": "general", "text": "今、落ち着きがなくそわそわしている", "reverse": False,
     "explanation": "精神的な不安定さを測定します（K6 参考）。",
     "advice_high": "グラウンディング（足裏の感覚に集中する）を試してみましょう。",
     "advice_low": "精神的に安定しています。"},
    {"id": 118, "category": "psychological_state", "subcategory": "general", "text": "最近、何をしても楽しめない", "reverse": False,
     "explanation": "快感消失を測定します。",
     "advice_high": "楽しめない状態が続く場合は、専門家への相談を検討しましょう。",
     "advice_low": "日常を楽しめています。"},
    {"id": 119, "category": "psychological_state", "subcategory": "general", "text": "今、全体的に心の状態は良いと感じる", "reverse": True,
     "explanation": "主観的な心理的健康度を測定する逆転項目です。",
     "advice_high": "心の状態が良好です。",
     "advice_low": "心の調子が優れない時は、無理をせず休息を取りましょう。"},
    {"id": 120, "category": "psychological_state", "subcategory": "general", "text": "今、自分で自分のことをケアできていると感じる", "reverse": True,
     "explanation": "セルフケアの自己評価を測定する逆転項目です。",
     "advice_high": "セルフケアが行き届いています。",
     "advice_low": "自分を大切にする時間を意識的に作りましょう。"},
]

# ID → 設問の辞書
QUESTION_BY_ID = {q["id"]: q for q in QUESTIONS}

# カテゴリ → 設問IDリストの辞書
CATEGORY_IDS = {}
for q in QUESTIONS:
    cat = q["category"]
    if cat not in CATEGORY_IDS:
        CATEGORY_IDS[cat] = []
    CATEGORY_IDS[cat].append(q["id"])
