# 感情チェック設問データ（200問）
# 参考尺度: STAXI-2, DERS, CERQ, FFMQ, PSS 日本語版

SCALE_LABELS = {
    1: "まったくそうでない",
    2: "少しそうだ",
    3: "かなりそうだ",
    4: "非常にそうだ",
}

QUESTIONS = [
    # ─── カテゴリ1: 怒り感情（状態怒り）─── #
    {"id": 1, "category": "anger", "subcategory": "state", "text": "今、とてもイライラしている", "reverse": False,
     "explanation": "現在の状態怒りを測定します。高スコアは今この瞬間の怒り感情が強いことを示します。",
     "advice_high": "今すぐ深呼吸を3回してみましょう。4秒吸って、7秒止めて、8秒で吐く「4-7-8呼吸法」が効果的です。",
     "advice_low": "今は穏やかな状態です。この感覚を大切にしてください。"},
    {"id": 2, "category": "anger", "subcategory": "state", "text": "今、怒りを感じている", "reverse": False,
     "explanation": "現在の怒り感情の存在を確認します。",
     "advice_high": "怒りはエネルギーです。散歩や軽い運動でそのエネルギーを発散させましょう。",
     "advice_low": "穏やかな状態が続いています。"},
    {"id": 3, "category": "anger", "subcategory": "state", "text": "今、かっとなりそうな感覚がある", "reverse": False,
     "explanation": "怒りが爆発しそうな状態を測定します。",
     "advice_high": "その場を一度離れることが有効です。トイレや外に出て気持ちをリセットしましょう。",
     "advice_low": "冷静を保てています。"},
    {"id": 4, "category": "anger", "subcategory": "state", "text": "今、ひどく腹が立っている", "reverse": False,
     "explanation": "強い怒り感情を測定します。",
     "advice_high": "怒りのピーク時は判断を避けましょう。10秒数えてから行動することを心がけてください。",
     "advice_low": "今は落ち着いた状態です。"},
    {"id": 5, "category": "anger", "subcategory": "state", "text": "今、誰かに怒りをぶつけたくなっている", "reverse": False,
     "explanation": "怒りの外向き表出衝動を測定します。",
     "advice_high": "衝動を感じたら、まず気持ちを書き出してみましょう。書くことで感情が整理されます。",
     "advice_low": "感情の衝動が抑えられています。"},
    {"id": 6, "category": "anger", "subcategory": "state", "text": "今、強い不満を感じている", "reverse": False,
     "explanation": "不満感情は怒りの前段階になることがあります。",
     "advice_high": "不満の原因を具体的に書き出し、自分でコントロールできることとそうでないことを分けてみましょう。",
     "advice_low": "今は満足度が高い状態です。"},
    {"id": 7, "category": "anger", "subcategory": "state", "text": "今、頭に血が上っている感じがする", "reverse": False,
     "explanation": "身体的な怒りの反応を測定します。",
     "advice_high": "冷たい水を飲む・手首を冷やすなど物理的なクールダウンが有効です。",
     "advice_low": "身体が穏やかな状態です。"},
    {"id": 8, "category": "anger", "subcategory": "state", "text": "今、誰かを責めたい気持ちがある", "reverse": False,
     "explanation": "他責傾向の感情状態を測定します。",
     "advice_high": "「相手はなぜそう行動したのか」を想像してみましょう。背景を知ると怒りが和らぐことがあります。",
     "advice_low": "今は他者への攻撃衝動が低い状態です。"},
    {"id": 9, "category": "anger", "subcategory": "state", "text": "今、何かを叩いたり壊したくなる気分だ", "reverse": False,
     "explanation": "怒りの身体的表出衝動を測定します。",
     "advice_high": "枕を叩く、新聞紙を破るなど安全な方法でエネルギーを発散させましょう。",
     "advice_low": "破壊的な衝動は感じられていません。"},
    {"id": 10, "category": "anger", "subcategory": "state", "text": "今、怒鳴りたい気分だ", "reverse": False,
     "explanation": "怒りの言語的表出衝動を測定します。",
     "advice_high": "大きな声を出したい衝動があるなら、一人でいられる場所に移動してから声に出してみましょう。",
     "advice_low": "声の衝動が抑えられています。"},

    # ─── カテゴリ1: 怒り感情（特性怒り）─── #
    {"id": 11, "category": "anger", "subcategory": "trait", "text": "些細なことでカッとなることが多い", "reverse": False,
     "explanation": "特性怒りの閾値の低さを測定します。高スコアは怒りの感受性が高いことを示します。",
     "advice_high": "怒りのトリガーをリストアップし、事前に対処法を準備しておくことが効果的です。",
     "advice_low": "怒りの閾値が適切に保たれています。"},
    {"id": 12, "category": "anger", "subcategory": "trait", "text": "批判されると激しく怒りを感じる", "reverse": False,
     "explanation": "批判への怒り反応を測定します。",
     "advice_high": "批判は自分の成長のためのフィードバックと捉える練習をしましょう。",
     "advice_low": "批判への耐性が保たれています。"},
    {"id": 13, "category": "anger", "subcategory": "trait", "text": "物事が思い通りにならないとすぐに怒りを感じる", "reverse": False,
     "explanation": "フラストレーション耐性の低さを測定します。",
     "advice_high": "「完璧でなくてよい」という考え方を意識的に持つようにしましょう。",
     "advice_low": "フラストレーション耐性が保たれています。"},
    {"id": 14, "category": "anger", "subcategory": "trait", "text": "待たされると強い苛立ちを感じる", "reverse": False,
     "explanation": "待機時の苛立ち反応を測定します。",
     "advice_high": "待ち時間を「自分だけの時間」として活用する方法を見つけましょう。",
     "advice_low": "待機時の耐性が保たれています。"},
    {"id": 15, "category": "anger", "subcategory": "trait", "text": "理不尽な扱いを受けると激しく怒る", "reverse": False,
     "explanation": "不公平感への怒り反応を測定します。",
     "advice_high": "「公平でない状況は存在する」という現実を受け入れる練習が助けになります。",
     "advice_low": "不公平への怒り反応が適切です。"},
    {"id": 16, "category": "anger", "subcategory": "trait", "text": "人々が自分に失礼だと感じるとすぐに怒る", "reverse": False,
     "explanation": "対人場面での怒り感受性を測定します。",
     "advice_high": "相手が失礼に見える行動をとる背景（疲れ・焦りなど）を想像してみましょう。",
     "advice_low": "対人場面での感情反応が安定しています。"},
    {"id": 17, "category": "anger", "subcategory": "trait", "text": "怒りを抑えるのが難しいと感じることが多い", "reverse": False,
     "explanation": "怒り抑制の難しさを測定します。",
     "advice_high": "怒りのエスカレートパターンを記録し、早い段階で気づく練習をしましょう。",
     "advice_low": "怒りの抑制が比較的うまくできています。"},
    {"id": 18, "category": "anger", "subcategory": "trait", "text": "一度怒ると怒りが消えるまでに時間がかかる", "reverse": False,
     "explanation": "怒りの持続時間を測定します。",
     "advice_high": "運動・入浴・睡眠など、怒りをリセットするルーティンを作りましょう。",
     "advice_low": "怒りの回復が早い傾向があります。"},
    {"id": 19, "category": "anger", "subcategory": "trait", "text": "怒りが爆発した後、激しく後悔することがある", "reverse": False,
     "explanation": "怒り爆発後の後悔を測定します。",
     "advice_high": "後悔は変化へのエネルギーです。次はどう対応するかを具体的に計画しましょう。",
     "advice_low": "怒りのコントロールが後悔を最小化できています。"},
    {"id": 20, "category": "anger", "subcategory": "trait", "text": "少しのことで怒りが爆発することがある", "reverse": False,
     "explanation": "怒りの爆発のしやすさを測定します。",
     "advice_high": "怒りが爆発する前のサインを知り、早めに対処する「アンガーアーリーウォーニング」を練習しましょう。",
     "advice_low": "怒りの爆発が抑制されています。"},
    {"id": 21, "category": "anger", "subcategory": "trait", "text": "仕事や家事が思い通りに進まないと腹が立つ", "reverse": False,
     "explanation": "日常場面での怒りを測定します。",
     "advice_high": "タスクを小分けにして「できたこと」に目を向けることで達成感を高めましょう。",
     "advice_low": "日常のフラストレーションへの耐性があります。"},
    {"id": 22, "category": "anger", "subcategory": "trait", "text": "自分の怒りをコントロールできていないと感じることが多い", "reverse": False,
     "explanation": "怒りコントロール感の欠如を測定します。",
     "advice_high": "感情日記をつけて怒りのパターンを把握することが第一歩です。",
     "advice_low": "怒りのコントロール感がある程度保たれています。"},

    # ─── カテゴリ1: 怒り感情（怒り表出）─── #
    {"id": 23, "category": "anger", "subcategory": "expression_out", "text": "怒ったとき、相手にきつい言葉をぶつけてしまう", "reverse": False,
     "explanation": "怒りの外向き言語的表出を測定します。",
     "advice_high": "言葉を発する前に3秒待つ習慣をつけましょう。「今言うべきか？」と自問することが有効です。",
     "advice_low": "怒りの言語的表出が抑制されています。"},
    {"id": 24, "category": "anger", "subcategory": "expression_out", "text": "怒ったとき、大きな声を出してしまう", "reverse": False,
     "explanation": "怒りの音声的表出を測定します。",
     "advice_high": "声が上がりそうになったら意識的に声のトーンを落とすと、感情も落ち着いてきます。",
     "advice_low": "怒りの音声的表出が抑制されています。"},
    {"id": 25, "category": "anger", "subcategory": "expression_out", "text": "怒ったとき、乱暴な行動をとることがある", "reverse": False,
     "explanation": "怒りの身体的表出を測定します。",
     "advice_high": "安全な環境でのエネルギー発散（スポーツ、クッションを叩くなど）を習慣にしましょう。",
     "advice_low": "身体的な怒りの表出が抑制されています。"},
    {"id": 26, "category": "anger", "subcategory": "expression_in", "text": "怒っても表に出さず内に秘めることが多い", "reverse": False,
     "explanation": "怒りの内向き表出を測定します。怒りを抑え込むことも長期的なストレスになります。",
     "advice_high": "信頼できる人に気持ちを話すか、日記に書くことで感情を安全に発散しましょう。",
     "advice_low": "怒りを適切に表現できています。"},
    {"id": 27, "category": "anger", "subcategory": "expression_in", "text": "怒りを感じても黙って我慢することが多い", "reverse": False,
     "explanation": "怒りの抑圧を測定します。",
     "advice_high": "「私は〜と感じた」という I メッセージで感情を伝える練習をしましょう。",
     "advice_low": "感情の抑圧が少ない傾向があります。"},
    {"id": 28, "category": "anger", "subcategory": "control", "text": "怒りを感じたとき、深呼吸して冷静になろうとする", "reverse": True,
     "explanation": "怒りの積極的制御を測定します。高スコアは良好な怒りコントロールを示します。",
     "advice_high": "素晴らしい対処法です。引き続き実践してください。",
     "advice_low": "深呼吸法（腹式呼吸）を日常的に練習し、怒り時にも使えるようにしましょう。"},
    {"id": 29, "category": "anger", "subcategory": "control", "text": "怒りを感じたとき、相手の立場に立って考えようとする", "reverse": True,
     "explanation": "視点取得による怒り制御を測定します。",
     "advice_high": "視点取得ができています。この習慣を大切にしてください。",
     "advice_low": "「相手はなぜそう行動したのか？」を意識的に考える練習をしましょう。"},
    {"id": 30, "category": "anger", "subcategory": "control", "text": "怒りを感じたとき、その場を離れて冷静になろうとする", "reverse": True,
     "explanation": "タイムアウト戦略による怒り制御を測定します。",
     "advice_high": "タイムアウト戦略を使えています。効果的な対処です。",
     "advice_low": "怒りを感じたらまず「少し席を外してきます」と言えるよう準備しておきましょう。"},

    # ─── カテゴリ2: 感情調節困難（DERS参考）─── #
    {"id": 31, "category": "regulation", "subcategory": "awareness", "text": "自分が何を感じているのかよくわからないことがある", "reverse": False,
     "explanation": "感情への気づきの欠如を測定します。感情に名前をつけられないと調節が難しくなります。",
     "advice_high": "「感情の輪（プルチックの感情の輪）」を参考に、今感じていることに名前をつける練習をしましょう。",
     "advice_low": "感情への気づきが良好です。"},
    {"id": 32, "category": "regulation", "subcategory": "awareness", "text": "動揺したとき、自分の感情がよくわからなくなる", "reverse": False,
     "explanation": "高覚醒状態での感情認識の困難さを測定します。",
     "advice_high": "感情が高まったとき、一度立ち止まって「今、何を感じているか」を3秒間考えましょう。",
     "advice_low": "高覚醒時も感情認識ができています。"},
    {"id": 33, "category": "regulation", "subcategory": "clarity", "text": "自分の感情を言葉で表現するのが苦手だ", "reverse": False,
     "explanation": "感情の言語化の困難さを測定します。",
     "advice_high": "日記に毎日の感情を書く練習が、感情の言語化能力を高めます。",
     "advice_low": "感情の言語化ができています。"},
    {"id": 34, "category": "regulation", "subcategory": "clarity", "text": "自分の感情がどこから来るのかよくわからない", "reverse": False,
     "explanation": "感情の原因への気づきの欠如を測定します。",
     "advice_high": "感情が生じたとき、その直前に何があったかを振り返るクセをつけましょう。",
     "advice_low": "感情の原因への理解があります。"},
    {"id": 35, "category": "regulation", "subcategory": "impulse", "text": "感情的になったとき、自分の行動をコントロールできなくなる", "reverse": False,
     "explanation": "感情的状態でのインパルスコントロールの困難さを測定します。",
     "advice_high": "感情が高まった時の「行動ルール」を事前に決めておきましょう（例：電話は1時間後にかける）。",
     "advice_low": "感情的状態でも行動制御ができています。"},
    {"id": 36, "category": "regulation", "subcategory": "impulse", "text": "感情に振り回されてしまうことがある", "reverse": False,
     "explanation": "感情に支配される頻度を測定します。",
     "advice_high": "感情は「通過する雲」のようなもの。流れていくのを観察する練習をしましょう。",
     "advice_low": "感情に振り回されることが少ない傾向があります。"},
    {"id": 37, "category": "regulation", "subcategory": "strategies", "text": "気分が悪いとき、そこから立ち直るのが難しい", "reverse": False,
     "explanation": "感情調節方略の欠如を測定します。",
     "advice_high": "気分を改善するための「回復ルーティン」を作りましょう（音楽、散歩、深呼吸など）。",
     "advice_low": "気分の回復力（レジリエンス）があります。"},
    {"id": 38, "category": "regulation", "subcategory": "strategies", "text": "不快な感情を感じると、ずっとそれにとらわれてしまう", "reverse": False,
     "explanation": "感情的とらわれを測定します。",
     "advice_high": "「今この瞬間」に注意を向けるマインドフルネス練習がとらわれを減らします。",
     "advice_low": "感情的なとらわれが少ない傾向があります。"},
    {"id": 39, "category": "regulation", "subcategory": "strategies", "text": "感情が非常に強くなると、どうにも対処できなくなる", "reverse": False,
     "explanation": "強い感情への対処能力を測定します。",
     "advice_high": "強い感情時の「緊急対処リスト」を作成しておきましょう（信頼できる人に連絡するなど）。",
     "advice_low": "強い感情への対処力があります。"},
    {"id": 40, "category": "regulation", "subcategory": "goals", "text": "感情が激しいと、目の前のことに集中できなくなる", "reverse": False,
     "explanation": "感情的状態での目標指向行動の困難さを測定します。",
     "advice_high": "タスクを極小化し、「今はこれだけやる」というミニゴールを設定しましょう。",
     "advice_low": "感情的状態でも集中が保てています。"},
    {"id": 41, "category": "regulation", "subcategory": "goals", "text": "強い感情を感じているとき、将来のことをうまく計画できない", "reverse": False,
     "explanation": "感情状態が認知機能に与える影響を測定します。",
     "advice_high": "感情が高まっているときは、重要な決断を先延ばしにする判断が賢明です。",
     "advice_low": "感情的状態でも計画能力が保たれています。"},
    {"id": 42, "category": "regulation", "subcategory": "non_acceptance", "text": "強い感情を感じると、そのままに受け入れることができない", "reverse": False,
     "explanation": "感情への非受容的反応を測定します。",
     "advice_high": "「感情はあって当然のもの」という考え方（感情受容）を練習しましょう。",
     "advice_low": "感情への受容的態度があります。"},
    {"id": 43, "category": "regulation", "subcategory": "non_acceptance", "text": "ネガティブな感情を感じると、それが必ず悪い結果をもたらすと思ってしまう", "reverse": False,
     "explanation": "感情についての否定的な信念を測定します。",
     "advice_high": "感情と結果は必ずしも連動しません。「感情を感じること」と「行動すること」は別物です。",
     "advice_low": "感情と結果を適切に区別できています。"},
    {"id": 44, "category": "regulation", "subcategory": "non_acceptance", "text": "怒りを感じると、自分がダメな人間だと感じてしまう", "reverse": False,
     "explanation": "感情についての自己批判的反応を測定します。",
     "advice_high": "怒りを感じることは人間として自然なことです。感情を持つこと自体を責めないでください。",
     "advice_low": "感情への自己批判が少ない傾向があります。"},
    {"id": 45, "category": "regulation", "subcategory": "non_acceptance", "text": "ネガティブな感情を感じると、自分を弱い人間だと感じる", "reverse": False,
     "explanation": "感情体験への自己評価の歪みを測定します。",
     "advice_high": "感情を感じることは弱さではなく、人間の豊かさです。セルフコンパッション（自己思いやり）を実践しましょう。",
     "advice_low": "感情体験への健全な自己評価があります。"},
    {"id": 46, "category": "regulation", "subcategory": "non_acceptance", "text": "不快な感情は認めてはいけないと思うことがある", "reverse": False,
     "explanation": "感情抑制の規則を測定します。",
     "advice_high": "「感情は感じてもよい」という許可を自分に与えましょう。抑圧は長期的にストレスを増やします。",
     "advice_low": "感情への許容的態度があります。"},
    {"id": 47, "category": "regulation", "subcategory": "impulse", "text": "感情的になると、人間関係に問題が生じることがある", "reverse": False,
     "explanation": "感情調節の失敗が対人関係に与える影響を測定します。",
     "advice_high": "感情が高まったとき、「後で話し合おう」と一時的に距離を置くコミュニケーションを練習しましょう。",
     "advice_low": "感情が対人関係への影響を最小限にできています。"},
    {"id": 48, "category": "regulation", "subcategory": "strategies", "text": "嫌な気持ちになると、すぐにそれを感じないようにしようとする", "reverse": False,
     "explanation": "感情の回避を測定します。",
     "advice_high": "感情を回避しようとすると逆効果になることがあります。少しだけ感情に寄り添う練習をしましょう。",
     "advice_low": "感情との接触を避けすぎていません。"},
    {"id": 49, "category": "regulation", "subcategory": "strategies", "text": "感情的な状態から、なかなか抜け出せない", "reverse": False,
     "explanation": "感情状態の持続性を測定します。",
     "advice_high": "気分転換の方法（運動・音楽・自然の中を歩く）を持っておくことが回復を早めます。",
     "advice_low": "感情状態からの回復が比較的スムーズです。"},
    {"id": 50, "category": "regulation", "subcategory": "awareness", "text": "感情をコントロールしようとすればするほど、うまくいかない感じがする", "reverse": False,
     "explanation": "感情制御のパラドックスを測定します。",
     "advice_high": "感情を「コントロール」しようとするより「受け入れる」ことが、逆に落ち着かせることがあります。",
     "advice_low": "感情制御において過度な努力をしていません。"},

    # ─── カテゴリ3: 認知的感情調節（CERQ参考）─── #
    {"id": 51, "category": "cognitive_regulation", "subcategory": "self_blame", "text": "嫌なことがあったとき、すべて自分のせいだと考えてしまう", "reverse": False,
     "explanation": "自己批判的な認知方略を測定します。過度な自己批判は抑うつにつながります。",
     "advice_high": "責任の所在を公平に見直しましょう。「自分・他者・状況」の3つの観点から考えてみてください。",
     "advice_low": "過度な自己批判をしていません。"},
    {"id": 52, "category": "cognitive_regulation", "subcategory": "self_blame", "text": "困難な状況では、自分の欠点や弱さを責めてしまう", "reverse": False,
     "explanation": "自己批判の強さを測定します。",
     "advice_high": "セルフコンパッション（自分を友人のように扱う）を実践しましょう。",
     "advice_low": "自己批判が適度に抑制されています。"},
    {"id": 53, "category": "cognitive_regulation", "subcategory": "self_blame", "text": "嫌な経験をしたとき、自分が悪かったと考え込む", "reverse": False,
     "explanation": "自己批判的な反芻を測定します。",
     "advice_high": "「こうすればよかった」という学習は大切ですが、それ以上の自責は必要ありません。",
     "advice_low": "自己批判的な考え込みが少ない傾向があります。"},
    {"id": 54, "category": "cognitive_regulation", "subcategory": "acceptance", "text": "起きてしまったことは仕方ないと受け入れることができる", "reverse": True,
     "explanation": "受容的な認知方略を測定します。高スコアは健全な受容を示します。",
     "advice_high": "受容ができています。この姿勢を大切にしてください。",
     "advice_low": "「変えられないことはある」という受容の練習をしましょう。"},
    {"id": 55, "category": "cognitive_regulation", "subcategory": "acceptance", "text": "嫌な経験は人生の一部として受け入れることができる", "reverse": True,
     "explanation": "人生全体での受容を測定します。",
     "advice_high": "人生の多様な経験を受け入れる姿勢があります。",
     "advice_low": "困難な経験も人生の学びの一部と捉えるリフレーミングを練習しましょう。"},
    {"id": 56, "category": "cognitive_regulation", "subcategory": "rumination", "text": "嫌なことを何度も思い返してしまう", "reverse": False,
     "explanation": "反芻思考を測定します。反芻は怒りや抑うつを悪化させます。",
     "advice_high": "反芻に気づいたら、注意を別のことに向ける「注意転換」を意識的に行いましょう。",
     "advice_low": "反芻思考が少ない傾向があります。"},
    {"id": 57, "category": "cognitive_regulation", "subcategory": "rumination", "text": "不快な経験を心の中で繰り返し考えてしまう", "reverse": False,
     "explanation": "反芻の頻度を測定します。",
     "advice_high": "「今この瞬間」への注意を意識的に戻すマインドフルネスが反芻を減らします。",
     "advice_low": "反芻が少ない傾向があります。"},
    {"id": 58, "category": "cognitive_regulation", "subcategory": "rumination", "text": "嫌な出来事についてずっと考え続けてしまう", "reverse": False,
     "explanation": "反芻の持続性を測定します。",
     "advice_high": "「この考えに今意味はあるか？」と問いかけることで反芻を中断できます。",
     "advice_low": "思考の持続が適切にコントロールされています。"},
    {"id": 59, "category": "cognitive_regulation", "subcategory": "positive_refocus", "text": "嫌なことがあっても、良いことについて考えるようにしている", "reverse": True,
     "explanation": "ポジティブな再焦点化を測定します。",
     "advice_high": "ポジティブな再焦点化ができています。",
     "advice_low": "嫌なことがあったとき、意識的に良いことを3つ思い出す練習をしましょう。"},
    {"id": 60, "category": "cognitive_regulation", "subcategory": "positive_refocus", "text": "不快な感情のとき、楽しい思い出を意識的に思い出す", "reverse": True,
     "explanation": "ポジティブな注意の転換を測定します。",
     "advice_high": "気分転換の認知方略を持っています。",
     "advice_low": "楽しい記憶のリストを作っておくと、つらいときに役立ちます。"},
    {"id": 61, "category": "cognitive_regulation", "subcategory": "positive_reappraisal", "text": "嫌な経験から学べることを探そうとする", "reverse": True,
     "explanation": "ポジティブな再評価を測定します。最も有効な感情調節方略の一つです。",
     "advice_high": "困難から学びを見つける力があります。素晴らしいです。",
     "advice_low": "「この経験から何を学べるか？」と自問する練習をしましょう。"},
    {"id": 62, "category": "cognitive_regulation", "subcategory": "positive_reappraisal", "text": "困難な状況でも、その中に良い点を見つけようとする", "reverse": True,
     "explanation": "リフレーミング能力を測定します。",
     "advice_high": "困難の中に良い点を見つける力があります。",
     "advice_low": "困難な状況でも「この中に何か良いことはないか？」と意識的に問いかけましょう。"},
    {"id": 63, "category": "cognitive_regulation", "subcategory": "positive_reappraisal", "text": "困難を成長の機会と考えるようにしている", "reverse": True,
     "explanation": "成長マインドセットを測定します。",
     "advice_high": "困難を成長機会として捉えられています。",
     "advice_low": "「この困難は自分を強くする」という視点を試してみましょう。"},
    {"id": 64, "category": "cognitive_regulation", "subcategory": "planning", "text": "困難な状況に直面したとき、どう対処するか計画を立てる", "reverse": True,
     "explanation": "問題解決志向の認知方略を測定します。",
     "advice_high": "計画立案による対処ができています。",
     "advice_low": "困難に直面したとき、紙に「できること」を書き出す習慣をつけましょう。"},
    {"id": 65, "category": "cognitive_regulation", "subcategory": "planning", "text": "問題が起きたとき、次のステップを具体的に考える", "reverse": True,
     "explanation": "行動計画の具体性を測定します。",
     "advice_high": "具体的な次のステップを考える力があります。",
     "advice_low": "問題に対して「次に自分ができること」を一つだけ決める練習をしましょう。"},
    {"id": 66, "category": "cognitive_regulation", "subcategory": "perspective", "text": "自分の状況は他の人のものよりはるかに悪いわけではないと考えようとする", "reverse": True,
     "explanation": "視点取得による下方比較を測定します。",
     "advice_high": "大局的な視点を持てています。",
     "advice_low": "「もっと困難な状況の人もいる」という視点を意識的に取り入れてみましょう。"},
    {"id": 67, "category": "cognitive_regulation", "subcategory": "perspective", "text": "物事を大局的な視点で見るようにしている", "reverse": True,
     "explanation": "大局的視野を測定します。",
     "advice_high": "広い視点で物事を見る力があります。",
     "advice_low": "10年後に今の問題はどれほど重要か？と問いかけてみましょう。"},
    {"id": 68, "category": "cognitive_regulation", "subcategory": "catastrophizing", "text": "嫌なことがあると、最悪の結果を想像してしまう", "reverse": False,
     "explanation": "破局化思考を測定します。破局化は怒りと不安を強めます。",
     "advice_high": "最悪のシナリオだけでなく、最善のシナリオと最も可能性の高いシナリオも考えましょう。",
     "advice_low": "破局化思考が少ない傾向があります。"},
    {"id": 69, "category": "cognitive_regulation", "subcategory": "catastrophizing", "text": "困難な状況で、すべてがうまくいかなくなると思う", "reverse": False,
     "explanation": "全般化した破局化思考を測定します。",
     "advice_high": "「すべて」という言葉に注意しましょう。実際には一部の問題です。",
     "advice_low": "全般化した否定的思考が少ない傾向があります。"},
    {"id": 70, "category": "cognitive_regulation", "subcategory": "catastrophizing", "text": "問題が起きると、取り返しのつかないことになると考える", "reverse": False,
     "explanation": "不可逆的な失敗への恐れを測定します。",
     "advice_high": "ほとんどの問題は時間と共に修正できます。「これは本当に取り返しがつかないか？」と問い直しましょう。",
     "advice_low": "問題への現実的な見方ができています。"},

    # ─── カテゴリ4: マインドフルネス（FFMQ参考）─── #
    {"id": 71, "category": "mindfulness", "subcategory": "observe", "text": "自分の周りの音・匂い・感触などの感覚に気づいている", "reverse": True,
     "explanation": "感覚への気づきを測定します。",
     "advice_high": "感覚への注意力があります。",
     "advice_low": "1日1回、5分間、周囲の感覚（音・匂い・感触）に意識を向ける練習をしましょう。"},
    {"id": 72, "category": "mindfulness", "subcategory": "observe", "text": "自分の感情がどのように変化しているかを観察できる", "reverse": True,
     "explanation": "感情の変化への気づきを測定します。",
     "advice_high": "感情観察の力があります。",
     "advice_low": "感情を「第三者の目で観察する」イメージで、感情の変化を追う練習をしましょう。"},
    {"id": 73, "category": "mindfulness", "subcategory": "observe", "text": "自分の呼吸や心拍などの身体感覚に注意を向けることができる", "reverse": True,
     "explanation": "身体感覚への気づきを測定します。",
     "advice_high": "身体感覚への注意力があります。",
     "advice_low": "ボディスキャン瞑想（全身の感覚を順番に感じる練習）を試してみましょう。"},
    {"id": 74, "category": "mindfulness", "subcategory": "observe", "text": "思考が浮かんでは消えるのを観察することができる", "reverse": True,
     "explanation": "思考への脱中心化を測定します。",
     "advice_high": "思考の観察ができています。",
     "advice_low": "思考を「空を流れる雲」として観察するイメージ練習をしましょう。"},
    {"id": 75, "category": "mindfulness", "subcategory": "observe", "text": "嬉しい感覚も不快な感覚も、同じように気づくことができる", "reverse": True,
     "explanation": "感情への平等な気づきを測定します。",
     "advice_high": "感情への公平な観察ができています。",
     "advice_low": "ポジティブな感覚にも意識的に気づく練習をしましょう。"},
    {"id": 76, "category": "mindfulness", "subcategory": "describe", "text": "自分の感情を言葉にすることができる", "reverse": True,
     "explanation": "感情の言語化能力を測定します。",
     "advice_high": "感情の言語化ができています。",
     "advice_low": "感情の言葉（「悲しい」「不安」「怒り」など）のボキャブラリーを広げましょう。"},
    {"id": 77, "category": "mindfulness", "subcategory": "describe", "text": "自分の気持ちを他者に説明することができる", "reverse": True,
     "explanation": "感情の対外的表現を測定します。",
     "advice_high": "感情の表現ができています。",
     "advice_low": "「今どんな気持ちか」を信頼できる人に話す機会を意識的に作りましょう。"},
    {"id": 78, "category": "mindfulness", "subcategory": "describe", "text": "感情を表現しようとしても適切な言葉が見つからないことがある", "reverse": False,
     "explanation": "感情の言語化の難しさを測定します。",
     "advice_high": "感情日記をつけて、感情を言語化する練習を重ねましょう。",
     "advice_low": "感情の言語化ができています。"},
    {"id": 79, "category": "mindfulness", "subcategory": "act_aware", "text": "今していることに完全に集中できている", "reverse": True,
     "explanation": "現在の活動への注意集中を測定します。",
     "advice_high": "今この瞬間への集中ができています。",
     "advice_low": "一つのことに集中する「シングルタスク」の練習をしましょう。"},
    {"id": 80, "category": "mindfulness", "subcategory": "act_aware", "text": "考えごとをしながら食事をするなど、自動的に行動していることが多い", "reverse": False,
     "explanation": "自動パイロット状態を測定します。",
     "advice_high": "食事中は食事に集中する「マインドフルイーティング」を試してみましょう。",
     "advice_low": "自動的な行動が少なく、意識的に行動できています。"},
    {"id": 81, "category": "mindfulness", "subcategory": "act_aware", "text": "将来のことや過去のことに気をとられて、今を見失うことがある", "reverse": False,
     "explanation": "現在からの注意の逸脱を測定します。",
     "advice_high": "過去・未来への心配が多い場合、「今ここ」に注意を戻す練習（アンカリング）が有効です。",
     "advice_low": "現在への集中ができています。"},
    {"id": 82, "category": "mindfulness", "subcategory": "act_aware", "text": "急いでいるときでも、一つひとつの動作を意識して行える", "reverse": True,
     "explanation": "高ストレス時の意識的行動を測定します。",
     "advice_high": "急いでいるときでも意識的な行動ができています。",
     "advice_low": "急いでいるときほど、意識的にゆっくり動く練習をしましょう。"},
    {"id": 83, "category": "mindfulness", "subcategory": "non_judge", "text": "自分の思考や感情を善悪で判断しないようにしている", "reverse": True,
     "explanation": "感情への非判断的態度を測定します。",
     "advice_high": "非判断的な姿勢があります。",
     "advice_low": "感情に「良い・悪い」のラベルを貼らず、ただ「○○という感情がある」と観察する練習をしましょう。"},
    {"id": 84, "category": "mindfulness", "subcategory": "non_judge", "text": "不快な感情を感じても、それを否定しないようにしている", "reverse": True,
     "explanation": "不快な感情への受容を測定します。",
     "advice_high": "不快な感情への受容的態度があります。",
     "advice_low": "不快な感情も「あってよいもの」として認める練習をしましょう。"},
    {"id": 85, "category": "mindfulness", "subcategory": "non_judge", "text": "自分の感情を批判せずに観察できる", "reverse": True,
     "explanation": "感情への自己批判のなさを測定します。",
     "advice_high": "感情への観察的態度があります。",
     "advice_low": "感情を「観察者」として見る練習をしましょう。あなたは感情ではなく、感情を持つ観察者です。"},
    {"id": 86, "category": "mindfulness", "subcategory": "non_judge", "text": "ネガティブな感情を感じることを恥ずかしいと思ってしまう", "reverse": False,
     "explanation": "感情体験への羞恥心を測定します。",
     "advice_high": "ネガティブな感情は人間として自然なことです。それを感じることへの羞恥心を手放しましょう。",
     "advice_low": "感情体験への羞恥心が少ない傾向があります。"},
    {"id": 87, "category": "mindfulness", "subcategory": "non_react", "text": "感情が湧いても、それにすぐに反応せず落ち着いていられる", "reverse": True,
     "explanation": "感情への非反応性を測定します。",
     "advice_high": "感情への反応が落ち着いています。",
     "advice_low": "感情を感じてから行動するまでに「間」を置く練習（間の呼吸）をしましょう。"},
    {"id": 88, "category": "mindfulness", "subcategory": "non_react", "text": "不快な気持ちが来ても、それをやり過ごすことができる", "reverse": True,
     "explanation": "感情の通過を促す能力を測定します。",
     "advice_high": "不快な感情をやり過ごす力があります。",
     "advice_low": "感情は「波」のようなもの。乗り越えれば必ず引きます。波が引くのを待つ練習をしましょう。"},
    {"id": 89, "category": "mindfulness", "subcategory": "non_react", "text": "嫌な考えが浮かんでも、それにとらわれずにいられる", "reverse": True,
     "explanation": "認知的脱フュージョンを測定します。",
     "advice_high": "思考へのとらわれが少ない傾向があります。",
     "advice_low": "「この考えはただの考えだ」と意識することで、考えとの距離を取る練習をしましょう。"},
    {"id": 90, "category": "mindfulness", "subcategory": "non_react", "text": "不快な感覚が来ても、すぐに反応しないようにしている", "reverse": True,
     "explanation": "身体的不快感への非反応性を測定します。",
     "advice_high": "身体感覚への反応が落ち着いています。",
     "advice_low": "不快な感覚に気づいたとき、まず「感じる」だけにとどまる練習をしましょう。"},

    # ─── カテゴリ5: ストレスと対処 ─── #
    {"id": 91, "category": "stress", "subcategory": "perceived_stress", "text": "予期せぬことが起きてうろたえることが多い", "reverse": False,
     "explanation": "ストレスへの反応性を測定します。",
     "advice_high": "「予期せぬことは起こり得る」という心構えを日ごろから持っておきましょう。",
     "advice_low": "予期しない出来事への適応力があります。"},
    {"id": 92, "category": "stress", "subcategory": "perceived_stress", "text": "生活の中の重要なことをコントロールできていない感じがする", "reverse": False,
     "explanation": "コントロール感の欠如を測定します。",
     "advice_high": "自分でコントロールできることに集中し、できないことは手放す練習をしましょう。",
     "advice_low": "コントロール感が保たれています。"},
    {"id": 93, "category": "stress", "subcategory": "perceived_stress", "text": "神経が張り詰めてストレスを強く感じることがある", "reverse": False,
     "explanation": "身体的・精神的なストレス体験を測定します。",
     "advice_high": "ストレスが高まっているサインです。意識的なリラクゼーションの時間を設けましょう。",
     "advice_low": "ストレスが比較的低い状態です。"},
    {"id": 94, "category": "stress", "subcategory": "perceived_stress", "text": "個人的な問題にうまく対処できていると感じる", "reverse": True,
     "explanation": "問題対処の自己効力感を測定します。",
     "advice_high": "問題対処能力への自信があります。",
     "advice_low": "小さな問題から一つずつ取り組んで成功体験を積みましょう。"},
    {"id": 95, "category": "stress", "subcategory": "perceived_stress", "text": "物事が自分の思い通りに進んでいる", "reverse": True,
     "explanation": "生活満足度を測定します。",
     "advice_high": "生活が順調に進んでいます。",
     "advice_low": "「思い通りでなくてよい部分」を認めることで、ストレスが軽減されます。"},
    {"id": 96, "category": "stress", "subcategory": "perceived_stress", "text": "自分の力ではどうにもならないことがあると感じてつらい", "reverse": False,
     "explanation": "無力感を測定します。",
     "advice_high": "「変えられないことを受け入れる知恵」（ニーバーの祈り）を実践しましょう。",
     "advice_low": "無力感が少ない傾向があります。"},
    {"id": 97, "category": "stress", "subcategory": "perceived_stress", "text": "困難が積み重なって乗り越えられないと感じることがある", "reverse": False,
     "explanation": "圧倒感を測定します。",
     "advice_high": "困難を一つずつ分解して、今日できる最小の一歩を決めましょう。",
     "advice_low": "困難への対処力があります。"},
    {"id": 98, "category": "stress", "subcategory": "perceived_stress", "text": "ストレスを感じていても、日常生活を維持できている", "reverse": True,
     "explanation": "ストレス下でのレジリエンスを測定します。",
     "advice_high": "ストレス下でも日常を維持する力があります。",
     "advice_low": "ストレス時に基本的なセルフケア（睡眠・食事・休息）を優先しましょう。"},
    {"id": 99, "category": "stress", "subcategory": "perceived_stress", "text": "自分の力の及ばないことに腹が立つことがよくある", "reverse": False,
     "explanation": "コントロール不可能な事柄への怒りを測定します。",
     "advice_high": "コントロールできないことへの怒りは消耗します。「自分の影響範囲」に集中しましょう。",
     "advice_low": "コントロール不可能な事柄への受容があります。"},
    {"id": 100, "category": "stress", "subcategory": "perceived_stress", "text": "今の自分のストレスレベルは管理可能だと感じる", "reverse": True,
     "explanation": "ストレス管理感を測定します。",
     "advice_high": "ストレス管理感があります。",
     "advice_low": "ストレスを具体的にリストアップし、優先順位をつけて管理しましょう。"},

    # ─── カテゴリ5: ソーシャルサポート ─── #
    {"id": 101, "category": "stress", "subcategory": "social_support", "text": "辛いときに話を聞いてくれる人がいる", "reverse": True,
     "explanation": "情緒的ソーシャルサポートを測定します。",
     "advice_high": "サポートしてくれる人がいます。その関係を大切にしてください。",
     "advice_low": "信頼できる人間関係を築くことが感情の安定に重要です。"},
    {"id": 102, "category": "stress", "subcategory": "social_support", "text": "困ったときに助けてくれる人がいる", "reverse": True,
     "explanation": "道具的ソーシャルサポートを測定します。",
     "advice_high": "サポートネットワークがあります。",
     "advice_low": "必要なときに助けを求めることは強さの表れです。一人で抱え込まないようにしましょう。"},
    {"id": 103, "category": "stress", "subcategory": "social_support", "text": "自分の気持ちを理解してくれる人がいる", "reverse": True,
     "explanation": "共感的サポートを測定します。",
     "advice_high": "理解してくれる人がいます。その関係を大切にしてください。",
     "advice_low": "自分の気持ちを分かち合える関係を少しずつ築いていきましょう。"},
    {"id": 104, "category": "stress", "subcategory": "social_support", "text": "孤独感を強く感じることが多い", "reverse": False,
     "explanation": "孤独感を測定します。",
     "advice_high": "孤独感が強い場合、まずは一人でできる趣味や活動に参加することから始めましょう。",
     "advice_low": "孤独感が少ない傾向があります。"},
    {"id": 105, "category": "stress", "subcategory": "social_support", "text": "悩みを打ち明けられる相手がいる", "reverse": True,
     "explanation": "信頼関係の有無を測定します。",
     "advice_high": "悩みを打ち明けられる人がいます。",
     "advice_low": "専門家（カウンセラーなど）に相談することも選択肢の一つです。"},
    {"id": 106, "category": "stress", "subcategory": "social_support", "text": "サポートを求めることに強い抵抗を感じる", "reverse": False,
     "explanation": "援助要請への抵抗を測定します。",
     "advice_high": "助けを求めることは人間として自然なことです。弱さではなく賢さの表れです。",
     "advice_low": "援助要請への抵抗が少ない傾向があります。"},

    # ─── カテゴリ5: コーピング方略 ─── #
    {"id": 107, "category": "stress", "subcategory": "coping", "text": "ストレスを感じたとき、運動や身体を動かすことで解消する", "reverse": True,
     "explanation": "運動コーピングを測定します。",
     "advice_high": "運動による対処ができています。非常に効果的な方法です。",
     "advice_low": "軽い散歩でも感情に良い影響を与えます。1日10分の歩行を試してみましょう。"},
    {"id": 108, "category": "stress", "subcategory": "coping", "text": "趣味や楽しいことで気持ちを切り替えることができる", "reverse": True,
     "explanation": "娯楽コーピングを測定します。",
     "advice_high": "趣味による気分転換ができています。",
     "advice_low": "小さくても楽しみを見つけることが感情の回復に役立ちます。"},
    {"id": 109, "category": "stress", "subcategory": "coping", "text": "ストレスを感じたとき、深呼吸やリラクゼーションを行う", "reverse": True,
     "explanation": "生理的コーピングを測定します。",
     "advice_high": "リラクゼーション技術を活用できています。",
     "advice_low": "「4-7-8呼吸法」や「プログレッシブ筋弛緩法」など、簡単なリラクゼーション法を覚えましょう。"},
    {"id": 110, "category": "stress", "subcategory": "coping", "text": "問題が起きたとき、直接解決しようとする", "reverse": True,
     "explanation": "問題焦点型コーピングを測定します。",
     "advice_high": "問題解決型の対処ができています。",
     "advice_low": "問題を「解決できること」と「受け入れるべきこと」に分類することから始めましょう。"},
    {"id": 111, "category": "stress", "subcategory": "coping", "text": "日記や記録をつけて感情を整理することがある", "reverse": True,
     "explanation": "表現的コーピングを測定します。",
     "advice_high": "感情の言語化による対処ができています。",
     "advice_low": "感情日記（1日5分）は感情の整理に非常に効果的です。"},
    {"id": 112, "category": "stress", "subcategory": "coping", "text": "ストレスが多いとき、食べ過ぎや飲み過ぎで紛らわそうとする", "reverse": False,
     "explanation": "回避的コーピングを測定します。",
     "advice_high": "食事や飲酒によるストレス対処は一時的です。より健全な対処法に置き換えましょう。",
     "advice_low": "回避的コーピングが少ない傾向があります。"},

    # ─── カテゴリ5: ウェルビーイング ─── #
    {"id": 113, "category": "stress", "subcategory": "wellbeing", "text": "毎日の生活に満足感を感じている", "reverse": True,
     "explanation": "生活満足度を測定します。",
     "advice_high": "生活への満足度があります。",
     "advice_low": "小さな喜びに気づく練習（感謝日記）が生活満足度を高めます。"},
    {"id": 114, "category": "stress", "subcategory": "wellbeing", "text": "自分の強みや良い点を意識できている", "reverse": True,
     "explanation": "自己認識の肯定性を測定します。",
     "advice_high": "自己の強みへの気づきがあります。",
     "advice_low": "「自分の得意なこと3つ」を書き出す練習をしましょう。"},
    {"id": 115, "category": "stress", "subcategory": "wellbeing", "text": "喜びや楽しさを感じる瞬間がある", "reverse": True,
     "explanation": "ポジティブ感情体験を測定します。",
     "advice_high": "ポジティブな感情体験があります。",
     "advice_low": "意識的に喜びを感じる活動を1日1つ取り入れましょう。"},
    {"id": 116, "category": "stress", "subcategory": "wellbeing", "text": "自分を大切にできていると感じる", "reverse": True,
     "explanation": "セルフケアへの意識を測定します。",
     "advice_high": "セルフケアができています。",
     "advice_low": "自分の基本的な欲求（睡眠・栄養・休息・つながり）を満たすことを優先しましょう。"},
    {"id": 117, "category": "stress", "subcategory": "wellbeing", "text": "感謝できることがたくさんあると感じる", "reverse": True,
     "explanation": "感謝の念を測定します。感謝は幸福感と関連しています。",
     "advice_high": "感謝の姿勢があります。",
     "advice_low": "毎日「感謝できること3つ」を書き出す感謝日記を実践しましょう。"},
    {"id": 118, "category": "stress", "subcategory": "wellbeing", "text": "休息や回復のための時間を十分にとれている", "reverse": True,
     "explanation": "回復のための時間確保を測定します。",
     "advice_high": "回復のための時間が確保できています。",
     "advice_low": "意識的に休息の時間を「予定に入れる」ことが回復を促します。"},
    {"id": 119, "category": "stress", "subcategory": "wellbeing", "text": "全体的に心の健康を保てていると感じる", "reverse": True,
     "explanation": "主観的な精神的健康感を測定します。",
     "advice_high": "心の健康感があります。",
     "advice_low": "心の健康のために、今日できる最小のことを一つ取り組んでみましょう。"},
    {"id": 120, "category": "stress", "subcategory": "wellbeing", "text": "目標に向かって前進している感覚がある", "reverse": True,
     "explanation": "目的意識と進歩感を測定します。",
     "advice_high": "目標への進歩感があります。",
     "advice_low": "小さな目標を設定し、達成を記録することで進歩感を得られます。"},

    # ─── 追加設問: 怒り・感情の深掘り ─── #
    {"id": 121, "category": "anger", "subcategory": "trait", "text": "怒りが収まった後、その怒りを振り返ることができる", "reverse": True,
     "explanation": "怒りへの内省能力を測定します。",
     "advice_high": "怒りへの内省ができています。",
     "advice_low": "怒りが収まった後に「何がトリガーだったか」を冷静に振り返る習慣をつけましょう。"},
    {"id": 122, "category": "anger", "subcategory": "trait", "text": "怒りを感じると体が緊張する（肩・首・拳など）", "reverse": False,
     "explanation": "怒りの身体的サインへの気づきを測定します。",
     "advice_high": "身体の緊張が怒りのサインです。早期に気づいて深呼吸などで緩めましょう。",
     "advice_low": "怒りの身体的反応が少ない傾向があります。"},
    {"id": 123, "category": "anger", "subcategory": "trait", "text": "怒りが爆発した後、マイナスの感情（落ち込みや後悔）が続く", "reverse": False,
     "explanation": "怒り後の感情的後遺症を測定します。",
     "advice_high": "怒りの爆発後の後遺症があります。怒りの予防が感情の安定につながります。",
     "advice_low": "怒り後の感情的な後遺症が少ない傾向があります。"},
    {"id": 124, "category": "anger", "subcategory": "control", "text": "怒りを感じる前に、自分のトリガーを認識できる", "reverse": True,
     "explanation": "怒りのトリガー認識を測定します。",
     "advice_high": "怒りのトリガー認識ができています。",
     "advice_low": "過去の怒りのパターンから自分のトリガーをリストアップしましょう。"},
    {"id": 125, "category": "anger", "subcategory": "control", "text": "怒りを感じたとき、何かに書き出して整理しようとする", "reverse": True,
     "explanation": "書くことによる怒り制御を測定します。",
     "advice_high": "書くことで感情整理ができています。",
     "advice_low": "怒りを感じたとき、その状況・感情・考えを紙に書き出す練習をしましょう。"},

    # ─── 追加設問: 感情調節の多様な側面 ─── #
    {"id": 126, "category": "regulation", "subcategory": "strategies", "text": "ネガティブな感情のとき、音楽や映画などで気分を変えることができる", "reverse": True,
     "explanation": "文化的コーピングを測定します。",
     "advice_high": "音楽や映画での気分転換ができています。",
     "advice_low": "お気に入りの音楽プレイリストを作っておくと、すぐに使えるリラックス法になります。"},
    {"id": 127, "category": "regulation", "subcategory": "strategies", "text": "感情的になりやすい時間帯や状況を知っている", "reverse": True,
     "explanation": "感情の状況依存性への気づきを測定します。",
     "advice_high": "自己のパターンへの気づきがあります。",
     "advice_low": "感情日記をつけて、感情が悪化しやすい時間帯・状況を把握しましょう。"},
    {"id": 128, "category": "regulation", "subcategory": "strategies", "text": "感情的になったとき、自分を落ち着かせる言葉（自己対話）を使う", "reverse": True,
     "explanation": "自己対話による感情調節を測定します。",
     "advice_high": "ポジティブな自己対話ができています。",
     "advice_low": "「大丈夫」「落ち着こう」「これは過ぎ去る」などの自己対話フレーズを用意しておきましょう。"},
    {"id": 129, "category": "regulation", "subcategory": "awareness", "text": "感情の変化に早い段階で気づくことができる", "reverse": True,
     "explanation": "感情の早期認識を測定します。",
     "advice_high": "感情の早期認識ができています。",
     "advice_low": "1時間ごとに「今の感情は？」と確認する練習（感情チェックイン）を試みましょう。"},
    {"id": 130, "category": "regulation", "subcategory": "strategies", "text": "感情的に困難なとき、専門家（カウンセラーなど）への相談を考える", "reverse": True,
     "explanation": "専門家への援助要請を測定します。",
     "advice_high": "専門家への相談も選択肢として持っています。",
     "advice_low": "専門家への相談は勇気ある選択です。必要と感じたらためらわず利用しましょう。"},

    # ─── 追加設問: 認知的柔軟性 ─── #
    {"id": 131, "category": "cognitive_regulation", "subcategory": "flexibility", "text": "物事を一面的に見ず、複数の視点から考えることができる", "reverse": True,
     "explanation": "認知的柔軟性を測定します。",
     "advice_high": "多角的視点があります。",
     "advice_low": "物事に対して「他の解釈はあるか？」と意識的に問いかける練習をしましょう。"},
    {"id": 132, "category": "cognitive_regulation", "subcategory": "flexibility", "text": "自分の意見が間違っていたと気づいたとき、意見を変えることができる", "reverse": True,
     "explanation": "認知的柔軟性・意見の修正を測定します。",
     "advice_high": "意見の柔軟な修正ができています。",
     "advice_low": "「意見を変えること」は知性の表れです。新しい情報に基づいて考えを更新しましょう。"},
    {"id": 133, "category": "cognitive_regulation", "subcategory": "flexibility", "text": "ストレスのかかる状況でも、冷静に考えることができる", "reverse": True,
     "explanation": "ストレス下での認知機能を測定します。",
     "advice_high": "ストレス下でも冷静な思考ができています。",
     "advice_low": "ストレス下での思考力を保つために、状況から少し距離を置く練習をしましょう。"},
    {"id": 134, "category": "cognitive_regulation", "subcategory": "flexibility", "text": "感情的になったとき、「事実」と「解釈」を区別できる", "reverse": True,
     "explanation": "認知行動療法的な事実・解釈の区別を測定します。",
     "advice_high": "事実と解釈の区別ができています。",
     "advice_low": "「これは事実か、それとも私の解釈か？」と問い直す習慣を身につけましょう。"},
    {"id": 135, "category": "cognitive_regulation", "subcategory": "flexibility", "text": "不確実な状況でも、過度に心配しないようにしている", "reverse": True,
     "explanation": "不確実性への耐性を測定します。",
     "advice_high": "不確実性への耐性があります。",
     "advice_low": "「わからないこと」をそのまま保留できる力（不確実性への耐性）を育てましょう。"},

    # ─── 追加設問: マインドフルネス応用 ─── #
    {"id": 136, "category": "mindfulness", "subcategory": "practice", "text": "毎日または週に数回、瞑想や深呼吸などのマインドフルネス練習をしている", "reverse": True,
     "explanation": "マインドフルネスの実践頻度を測定します。",
     "advice_high": "定期的な実践があります。継続してください。",
     "advice_low": "1日5分の呼吸瞑想から始めてみましょう。継続することで効果が現れます。"},
    {"id": 137, "category": "mindfulness", "subcategory": "practice", "text": "食事・歩行・シャワーなど日常活動をゆっくり味わって行う", "reverse": True,
     "explanation": "日常活動でのマインドフルネスを測定します。",
     "advice_high": "日常のマインドフルネスが実践できています。",
     "advice_low": "今日の食事を一口ずつ意識して味わうことから始めましょう。"},
    {"id": 138, "category": "mindfulness", "subcategory": "act_aware", "text": "スマートフォンなどで気が散り、今やっていることに集中できないことが多い", "reverse": False,
     "explanation": "デジタルディストラクションを測定します。",
     "advice_high": "特定の時間帯にスマートフォンを置く「デジタルデトックス」を試してみましょう。",
     "advice_low": "デジタルの誘惑に負けにくい傾向があります。"},
    {"id": 139, "category": "mindfulness", "subcategory": "observe", "text": "自然の音・光・風などに意識的に気づくことができる", "reverse": True,
     "explanation": "自然への感覚的気づきを測定します。",
     "advice_high": "自然への豊かな気づきがあります。",
     "advice_low": "毎日1分、空や植物などを意識的に見る時間を作りましょう。"},
    {"id": 140, "category": "mindfulness", "subcategory": "non_judge", "text": "自分の失敗に対して、友人に対するような優しさで接することができる", "reverse": True,
     "explanation": "セルフコンパッションを測定します。",
     "advice_high": "セルフコンパッションがあります。",
     "advice_low": "自分を友人のように扱う「セルフコンパッション」の練習をしましょう。失敗したとき「友人にどう声をかけるか？」を想像してみてください。"},

    # ─── 追加設問: 怒りと人間関係 ─── #
    {"id": 141, "category": "anger", "subcategory": "interpersonal", "text": "怒りを感じたとき、相手との関係を壊さないよう配慮できる", "reverse": True,
     "explanation": "対人場面での怒り制御を測定します。",
     "advice_high": "対人場面での怒り制御ができています。",
     "advice_low": "怒りを感じたとき「これを言ったら関係に影響するか？」と一瞬考える習慣をつけましょう。"},
    {"id": 142, "category": "anger", "subcategory": "interpersonal", "text": "職場や家庭での怒りを家に持ち帰らないようにしている", "reverse": True,
     "explanation": "場面間の感情の持ち越しを測定します。",
     "advice_high": "感情の場面間の移行が適切にできています。",
     "advice_low": "帰宅前に「気持ちの切り替えルーティン」（例：好きな音楽を聴く）を作りましょう。"},
    {"id": 143, "category": "anger", "subcategory": "interpersonal", "text": "怒りを感じても、穏やかに自分の気持ちを伝えることができる", "reverse": True,
     "explanation": "アサーティブコミュニケーションを測定します。",
     "advice_high": "アサーティブな感情表現ができています。",
     "advice_low": "「私は〜のとき、〜と感じました」という I メッセージの練習をしましょう。"},
    {"id": 144, "category": "anger", "subcategory": "interpersonal", "text": "怒りの後、相手に謝罪や和解を求めることができる", "reverse": True,
     "explanation": "修復行動の能力を測定します。",
     "advice_high": "修復行動ができています。",
     "advice_low": "「ごめん、さっきは言い過ぎた」という一言が関係修復に大きく効きます。"},
    {"id": 145, "category": "anger", "subcategory": "interpersonal", "text": "他者の怒りに対して、冷静に対応できる", "reverse": True,
     "explanation": "他者の感情への反応の落ち着きを測定します。",
     "advice_high": "他者の怒りへの冷静な対応ができています。",
     "advice_low": "他者の感情をもらいやすいなら、一歩引いた「観察者の立場」を意識する練習をしましょう。"},

    # ─── 追加設問: 感情と身体 ─── #
    {"id": 146, "category": "regulation", "subcategory": "somatic", "text": "感情が高まると、身体症状（頭痛・胃痛・肩こりなど）が出やすい", "reverse": False,
     "explanation": "感情の身体化を測定します。",
     "advice_high": "感情の身体化があります。定期的なストレッチや入浴で身体の緊張を解放しましょう。",
     "advice_low": "感情の身体化が少ない傾向があります。"},
    {"id": 147, "category": "regulation", "subcategory": "somatic", "text": "身体を動かすことで気持ちが楽になることを知っている", "reverse": True,
     "explanation": "運動と感情の関係への気づきを測定します。",
     "advice_high": "身体と感情の関係を理解しています。",
     "advice_low": "軽い散歩や体操でも感情が和らぐことがあります。試してみてください。"},
    {"id": 148, "category": "regulation", "subcategory": "somatic", "text": "睡眠が不十分のとき、感情コントロールが難しくなる", "reverse": False,
     "explanation": "睡眠と感情調節の関係を測定します。",
     "advice_high": "睡眠不足が感情に影響しているようです。睡眠の質を高めることが感情安定につながります。",
     "advice_low": "睡眠の影響が少ない傾向があります。"},
    {"id": 149, "category": "regulation", "subcategory": "somatic", "text": "空腹や疲れを感じると、感情のコントロールが難しくなる", "reverse": False,
     "explanation": "生理的状態と感情調節の関係を測定します（HALT: Hungry, Angry, Lonely, Tired）。",
     "advice_high": "空腹・疲れが感情に影響していることがわかっています。基本的なセルフケアを優先しましょう。",
     "advice_low": "生理的状態の影響が少ない傾向があります。"},
    {"id": 150, "category": "regulation", "subcategory": "somatic", "text": "ゆっくりとした深呼吸で身体の緊張が和らぐことを体感している", "reverse": True,
     "explanation": "呼吸法の効果への体感を測定します。",
     "advice_high": "深呼吸の効果を体感しています。",
     "advice_low": "腹式呼吸を10回ゆっくり行うと、副交感神経が働き緊張が和らぎます。"},

    # ─── 追加設問: 感情の多様な側面（計150→200に向けた拡張）─── #
    {"id": 151, "category": "anger", "subcategory": "state", "text": "今、穏やかで平和な気持ちでいる", "reverse": True,
     "explanation": "現在の平穏状態を測定します。",
     "advice_high": "今は穏やかな状態です。この感覚を大切にしてください。",
     "advice_low": "今この瞬間の穏やかさに意識を向けましょう。"},
    {"id": 152, "category": "regulation", "subcategory": "clarity", "text": "今の自分の感情状態を正確に把握できている", "reverse": True,
     "explanation": "現在の感情への明確な気づきを測定します。",
     "advice_high": "感情の明確な把握ができています。",
     "advice_low": "「今どんな感情か」を3つの言葉で表現する練習をしましょう。"},
    {"id": 153, "category": "cognitive_regulation", "subcategory": "acceptance", "text": "自分のコントロール外のことについて、手放すことができる", "reverse": True,
     "explanation": "手放し（レティング・ゴー）の能力を測定します。",
     "advice_high": "手放しができています。",
     "advice_low": "「これは私がコントロールできることか？」と問いかけ、できないものは手放す練習をしましょう。"},
    {"id": 154, "category": "mindfulness", "subcategory": "observe", "text": "今この瞬間の自分の内側（感情・思考・身体感覚）に気づいている", "reverse": True,
     "explanation": "現在瞬間への気づきを測定します。",
     "advice_high": "現在瞬間への気づきがあります。",
     "advice_low": "今この瞬間、自分の中で何が起きているかをゆっくりスキャンしてみましょう。"},
    {"id": 155, "category": "stress", "subcategory": "wellbeing", "text": "今日1日、心地よい瞬間が少なくとも一つあった", "reverse": True,
     "explanation": "日常のポジティブ体験を測定します。",
     "advice_high": "今日も良い瞬間があったことに気づけています。",
     "advice_low": "意識的にポジティブな体験を作る「喜びのスケジューリング」を試してみましょう。"},
    {"id": 156, "category": "anger", "subcategory": "trait", "text": "自分が怒りやすいパターン（時間帯・状況・相手）を知っている", "reverse": True,
     "explanation": "怒りのトリガーパターンへの自己認識を測定します。",
     "advice_high": "自己のパターンへの認識があります。",
     "advice_low": "感情日記で「いつ・どこで・誰と・どんな状況で」怒りが生じるかを記録しましょう。"},
    {"id": 157, "category": "regulation", "subcategory": "impulse", "text": "衝動的な行動をとる前に、少し立ち止まることができる", "reverse": True,
     "explanation": "衝動抑制能力を測定します。",
     "advice_high": "衝動抑制ができています。",
     "advice_low": "「3秒待つ」ルールを設けましょう。衝動を感じたら3秒数えてから行動してください。"},
    {"id": 158, "category": "cognitive_regulation", "subcategory": "positive_reappraisal", "text": "困難な経験を通じて自分が成長したと感じることがある", "reverse": True,
     "explanation": "外傷後成長（PTG）的な視点を測定します。",
     "advice_high": "困難からの成長を感じられています。",
     "advice_low": "過去に乗り越えた困難を振り返り、「あの時から何を学んだか」を考えてみましょう。"},
    {"id": 159, "category": "mindfulness", "subcategory": "non_judge", "text": "失敗したとき、過度に自分を責めずにいられる", "reverse": True,
     "explanation": "失敗への自己批判の抑制を測定します。",
     "advice_high": "失敗への適切な自己評価ができています。",
     "advice_low": "「失敗は学習の一部」という考え方を取り入れ、自己批判を和らげましょう。"},
    {"id": 160, "category": "stress", "subcategory": "coping", "text": "ストレスを感じたとき、問題を小さく分割して取り組める", "reverse": True,
     "explanation": "問題の分割対処を測定します。",
     "advice_high": "問題の分割対処ができています。",
     "advice_low": "大きな問題を「今日できること」に分割することで、圧倒感が減ります。"},

    # ─── さらなる追加設問（161〜200）─── #
    {"id": 161, "category": "anger", "subcategory": "state", "text": "今、誰かに対して不満を持っている", "reverse": False,
     "explanation": "対人不満感を測定します。",
     "advice_high": "相手に対する不満の具体的な内容を書き出し、「伝えるべきか・手放すか」を考えましょう。",
     "advice_low": "対人不満が少ない状態です。"},
    {"id": 162, "category": "anger", "subcategory": "state", "text": "今、自分の状況に対して不公平だと感じている", "reverse": False,
     "explanation": "不公平感を測定します。",
     "advice_high": "不公平感を感じているとき、「変えられることと変えられないこと」を分けて考えましょう。",
     "advice_low": "今は状況への受容ができています。"},
    {"id": 163, "category": "regulation", "subcategory": "strategies", "text": "ネガティブな感情に飲み込まれないための方法を持っている", "reverse": True,
     "explanation": "感情対処の方法論の有無を測定します。",
     "advice_high": "感情対処の方法を持っています。",
     "advice_low": "自分だけの「感情対処ツールキット」（呼吸法・音楽・言葉など）を作りましょう。"},
    {"id": 164, "category": "regulation", "subcategory": "strategies", "text": "感情の波が来ても、それが過ぎ去るまで耐えられる", "reverse": True,
     "explanation": "感情的苦痛への耐性を測定します。",
     "advice_high": "苦痛耐性があります。",
     "advice_low": "感情の波は必ず引きます。「この感情はいつか終わる」と自分に言い聞かせましょう。"},
    {"id": 165, "category": "cognitive_regulation", "subcategory": "rumination", "text": "過去の失敗や恥ずかしい出来事を繰り返し思い出してしまう", "reverse": False,
     "explanation": "過去への反芻を測定します。",
     "advice_high": "過去への反芻が多い場合、「過去は変えられない・今だけが変えられる」という視点を持ちましょう。",
     "advice_low": "過去への反芻が少ない傾向があります。"},
    {"id": 166, "category": "cognitive_regulation", "subcategory": "rumination", "text": "誰かに怒りを感じた後、その場面を何度も思い返す", "reverse": False,
     "explanation": "怒りに関連した反芻を測定します。",
     "advice_high": "怒りの反芻は怒りを増幅させます。意識的に注意を別のことに向けましょう。",
     "advice_low": "怒りの反芻が少ない傾向があります。"},
    {"id": 167, "category": "mindfulness", "subcategory": "act_aware", "text": "一度に複数のことを考えながら作業することが多い", "reverse": False,
     "explanation": "マルチタスクによる注意の分散を測定します。",
     "advice_high": "一つのことに集中するシングルタスクを意識的に練習しましょう。",
     "advice_low": "シングルタスクの傾向があります。"},
    {"id": 168, "category": "mindfulness", "subcategory": "non_react", "text": "誰かの言葉や行動にすぐに反応する前に、一呼吸置くことができる", "reverse": True,
     "explanation": "刺激-反応の間に「間」を置く能力を測定します。",
     "advice_high": "一呼吸置く力があります。",
     "advice_low": "「刺激→反応」の間に「選択の空間」があることを意識しましょう。"},
    {"id": 169, "category": "stress", "subcategory": "perceived_stress", "text": "最近、何事にも気力が沸かないことがある", "reverse": False,
     "explanation": "エネルギーの低下を測定します。",
     "advice_high": "エネルギーが低下しているサインです。睡眠・休息・好きなことに時間を使いましょう。",
     "advice_low": "気力が保たれています。"},
    {"id": 170, "category": "stress", "subcategory": "perceived_stress", "text": "最近、些細なことが気になってしょうがない", "reverse": False,
     "explanation": "過敏性の増大を測定します。",
     "advice_high": "過敏性が高まっています。ストレスのサインかもしれません。意識的なリラックスを心がけましょう。",
     "advice_low": "過敏性が低い状態です。"},
    {"id": 171, "category": "anger", "subcategory": "trait", "text": "怒りの感情が、後で恥ずかしさや罪悪感に変わることがある", "reverse": False,
     "explanation": "怒り後の二次感情を測定します。",
     "advice_high": "怒りの後の後悔サイクルがあります。怒りの予防に取り組むことでこのサイクルを断ち切れます。",
     "advice_low": "怒り後の二次感情が少ない傾向があります。"},
    {"id": 172, "category": "regulation", "subcategory": "awareness", "text": "自分が感情的になっていることに、その場で気づける", "reverse": True,
     "explanation": "感情状態のリアルタイムモニタリングを測定します。",
     "advice_high": "リアルタイムの感情モニタリングができています。",
     "advice_low": "感情が高まっているとき、早いサイン（声が大きくなる・心臓がドキドキするなど）を覚えましょう。"},
    {"id": 173, "category": "cognitive_regulation", "subcategory": "self_blame", "text": "物事がうまくいかないとき、すぐに自分を責めてしまう", "reverse": False,
     "explanation": "自己批判の即時性を測定します。",
     "advice_high": "自己批判を感じたとき「友人だったらどう言うか？」と問いかけましょう。",
     "advice_low": "即座の自己批判が少ない傾向があります。"},
    {"id": 174, "category": "cognitive_regulation", "subcategory": "other_blame", "text": "物事がうまくいかないとき、他者や状況のせいにしてしまう", "reverse": False,
     "explanation": "他責傾向を測定します。",
     "advice_high": "他責は問題解決を妨げることがあります。「自分でできること」に焦点を当てましょう。",
     "advice_low": "他責傾向が少ない傾向があります。"},
    {"id": 175, "category": "mindfulness", "subcategory": "practice", "text": "定期的に感謝を意識する時間を持っている", "reverse": True,
     "explanation": "感謝の実践を測定します。",
     "advice_high": "感謝の実践があります。",
     "advice_low": "毎晩寝る前に「今日感謝できること3つ」を思い浮かべる習慣をつけましょう。"},
    {"id": 176, "category": "stress", "subcategory": "social_support", "text": "人間関係から力や喜びをもらえていると感じる", "reverse": True,
     "explanation": "対人関係からの活力を測定します。",
     "advice_high": "人間関係から活力を得られています。",
     "advice_low": "意識的に人との交流を増やすことで、感情的なサポートが得られます。"},
    {"id": 177, "category": "stress", "subcategory": "coping", "text": "ストレスを発散するための健全な方法を複数持っている", "reverse": True,
     "explanation": "コーピングレパートリーの豊富さを測定します。",
     "advice_high": "複数の対処法を持っています。",
     "advice_low": "ストレス発散リスト（運動・音楽・呼吸・会話など）を作り、試してみましょう。"},
    {"id": 178, "category": "regulation", "subcategory": "strategies", "text": "感情が乱れたとき、自然の中を歩いたり空を見上げたりする", "reverse": True,
     "explanation": "自然療法的コーピングを測定します。",
     "advice_high": "自然を使った回復ができています。",
     "advice_low": "自然の中での短い散歩（10〜15分）は気分を改善する効果があります。"},
    {"id": 179, "category": "anger", "subcategory": "control", "text": "怒りを感じたとき、ユーモアや笑いで和らげることができる", "reverse": True,
     "explanation": "ユーモアによる怒り制御を測定します。",
     "advice_high": "ユーモアによる感情転換ができています。",
     "advice_low": "深刻な状況でも「可笑しさ」を見つける視点が、怒りを和らげることがあります。"},
    {"id": 180, "category": "cognitive_regulation", "subcategory": "planning", "text": "困難が起きたとき、誰かに相談するなどサポートを求める計画を立てられる", "reverse": True,
     "explanation": "サポート活用の計画性を測定します。",
     "advice_high": "サポートを求める計画が立てられています。",
     "advice_low": "「困ったときに相談できる人リスト」を作っておきましょう。"},
    {"id": 181, "category": "anger", "subcategory": "state", "text": "今、心が落ち着いている", "reverse": True,
     "explanation": "現在の心の平静を測定します。",
     "advice_high": "今、心が落ち着いています。",
     "advice_low": "今この瞬間に意識を向け、呼吸に集中してみましょう。"},
    {"id": 182, "category": "regulation", "subcategory": "strategies", "text": "感情を整理するために、創造的な活動（絵を描く、音楽を演奏するなど）を行う", "reverse": True,
     "explanation": "創造的コーピングを測定します。",
     "advice_high": "創造的な感情表現ができています。",
     "advice_low": "創造的な活動（絵・書・音楽・料理など）は感情の発散に効果的です。"},
    {"id": 183, "category": "mindfulness", "subcategory": "observe", "text": "会話中に相手の表情や声のトーンに気づくことができる", "reverse": True,
     "explanation": "対人場面での気づき力を測定します。",
     "advice_high": "対人場面での気づき力があります。",
     "advice_low": "会話中に相手の非言語的サインに注意を向ける練習をしましょう。"},
    {"id": 184, "category": "cognitive_regulation", "subcategory": "perspective", "text": "10年後に振り返ったとき、今の問題は小さく見えるだろうと思える", "reverse": True,
     "explanation": "時間的視点取得を測定します。",
     "advice_high": "長期的な視点を持てています。",
     "advice_low": "「10年後の自分はこの問題をどう見るか？」という問いかけをしてみましょう。"},
    {"id": 185, "category": "stress", "subcategory": "wellbeing", "text": "今日、自分のために何か良いことをした（または予定している）", "reverse": True,
     "explanation": "セルフケア行動を測定します。",
     "advice_high": "セルフケア行動があります。",
     "advice_low": "今日、自分のための小さな良いことを一つ決めて実行しましょう。"},
    {"id": 186, "category": "anger", "subcategory": "trait", "text": "強いストレス状態にあるとき、怒りやすくなると感じる", "reverse": False,
     "explanation": "ストレスと怒りの関係への気づきを測定します。",
     "advice_high": "ストレスが怒りのトリガーになるパターンがあります。ストレス管理が怒り管理の鍵です。",
     "advice_low": "ストレスによる怒りの増幅が少ない傾向があります。"},
    {"id": 187, "category": "regulation", "subcategory": "awareness", "text": "感情的になる前に、自分の体の変化（緊張・心拍増加など）に気づける", "reverse": True,
     "explanation": "感情の身体的前兆への気づきを測定します。",
     "advice_high": "感情の前兆への気づきがあります。早期対処につながります。",
     "advice_low": "定期的なボディスキャンで身体の緊張に気づく練習をしましょう。"},
    {"id": 188, "category": "cognitive_regulation", "subcategory": "positive_reappraisal", "text": "嫌な出来事について、「おかげで○○できた」という視点を持てることがある", "reverse": True,
     "explanation": "感謝的リフレーミングを測定します。",
     "advice_high": "感謝的なリフレーミングができています。",
     "advice_low": "嫌な経験について「この経験があったからこそ」という視点を探してみましょう。"},
    {"id": 189, "category": "mindfulness", "subcategory": "non_judge", "text": "自分の弱さや限界を認めることができる", "reverse": True,
     "explanation": "脆弱性の受容を測定します。",
     "advice_high": "自分の弱さを認める強さがあります。",
     "advice_low": "弱さを認めることは弱さではなく、勇気です。「完璧でなくてよい」と自分に許可しましょう。"},
    {"id": 190, "category": "stress", "subcategory": "coping", "text": "感情的になったとき、プロフェッショナルな姿勢を保てる", "reverse": True,
     "explanation": "職業的場面での感情調節を測定します。",
     "advice_high": "職業的場面での感情コントロールができています。",
     "advice_low": "職場での感情表現のルールを自分で設けましょう（例：感情が高まったら会議室で一人5分過ごす）。"},
    {"id": 191, "category": "anger", "subcategory": "control", "text": "「今、怒りを感じている」と言語化することで、少し冷静になれる", "reverse": True,
     "explanation": "感情のラベリングによる鎮静効果への気づきを測定します。",
     "advice_high": "感情のラベリングが有効です。この方法を続けましょう。",
     "advice_low": "感情に名前をつける（ラベリング）練習をしましょう。「今、怒りを感じている」と言語化するだけで脳が落ち着きます。"},
    {"id": 192, "category": "regulation", "subcategory": "strategies", "text": "感情が乱れたとき、信頼できる人に連絡することができる", "reverse": True,
     "explanation": "サポートの活用を測定します。",
     "advice_high": "サポートの活用ができています。",
     "advice_low": "感情が乱れたとき「まず一人で解決しなければ」という思い込みを手放しましょう。"},
    {"id": 193, "category": "cognitive_regulation", "subcategory": "flexibility", "text": "状況に合わせて、自分の感情表現を調整できる", "reverse": True,
     "explanation": "感情表現の文脈適応性を測定します。",
     "advice_high": "状況に応じた感情調節ができています。",
     "advice_low": "「今この場で感情を表現するのは適切か？」と一瞬考える習慣をつけましょう。"},
    {"id": 194, "category": "mindfulness", "subcategory": "act_aware", "text": "食事・入浴・就寝の時間を規則的に保つよう意識している", "reverse": True,
     "explanation": "生活リズムの意識的維持を測定します。",
     "advice_high": "規則的な生活リズムが感情の安定を支えています。",
     "advice_low": "規則的な睡眠・食事・活動時間が感情調節の基盤になります。"},
    {"id": 195, "category": "stress", "subcategory": "wellbeing", "text": "自分の人生に意味や目的を感じている", "reverse": True,
     "explanation": "ユーダイモニア的幸福感を測定します。",
     "advice_high": "人生の意味や目的を感じられています。",
     "advice_low": "「自分が大切にしていること（価値観）」を書き出してみましょう。それが意味の源になります。"},
    {"id": 196, "category": "anger", "subcategory": "trait", "text": "自分の怒りに気づき、それを適切に管理できると感じる", "reverse": True,
     "explanation": "怒り管理の自己効力感を測定します。",
     "advice_high": "怒り管理への自己効力感があります。",
     "advice_low": "小さな怒り管理の成功体験を積み重ねることで、自己効力感が高まります。"},
    {"id": 197, "category": "regulation", "subcategory": "strategies", "text": "感情的な問題を友人や家族と率直に話し合うことができる", "reverse": True,
     "explanation": "感情のオープンな対話を測定します。",
     "advice_high": "感情についてオープンに話せています。",
     "advice_low": "感情について話すことは関係を深めます。小さなことから始めて練習しましょう。"},
    {"id": 198, "category": "cognitive_regulation", "subcategory": "acceptance", "text": "不完全な自分を受け入れることができる", "reverse": True,
     "explanation": "自己受容を測定します。",
     "advice_high": "自己受容ができています。",
     "advice_low": "「完璧でない自分も、今のままで価値がある」という自己受容の練習をしましょう。"},
    {"id": 199, "category": "mindfulness", "subcategory": "non_judge", "text": "今日の自分の感情や行動について、穏やかに振り返ることができる", "reverse": True,
     "explanation": "セルフリフレクションの質を測定します。",
     "advice_high": "穏やかな自己振り返りができています。",
     "advice_low": "今日の振り返りを日記に書く際、批判ではなく「観察者として記録する」姿勢で行いましょう。"},
    {"id": 200, "category": "stress", "subcategory": "wellbeing", "text": "全体的に、今の自分の感情状態に満足している", "reverse": True,
     "explanation": "総合的な感情的幸福感を測定します。",
     "advice_high": "感情的な満足感があります。今日のセルフチェックよくできました。",
     "advice_low": "感情の改善は一歩ずつ進むものです。今日チェックしたことを小さな一歩として大切にしてください。"},
]

# カテゴリごとの質問IDを検索しやすくする
CATEGORY_IDS = {}
for q in QUESTIONS:
    cat = q["category"]
    if cat not in CATEGORY_IDS:
        CATEGORY_IDS[cat] = []
    CATEGORY_IDS[cat].append(q["id"])

# IDで検索するための辞書
QUESTION_BY_ID = {q["id"]: q for q in QUESTIONS}
